<?php $var_m_zz_design = new m_zz_designModel; ?>
<?php $var_permits_menu_value = $var_m_zz_design->sql_permits_menu_value(); ?>
<?php $var_user_session = $var_m_zz_design->sql_user_session(); ?>

<?php $var_m_azp_user = new m_azp_userModel; ?>
<?php # Instanciado funciones de la clase y asignando a variable
	if (false != $var_sql = $var_m_azp_user->sql_select_tc_azp_user_role()) {
		# Recorriendo filas de los resultados de la base de datos
		foreach ($var_sql as $key => $value):
			# Imprimiendo cada uno de los resultados recorridos de las filas
			$var_appl = $value[d_azp_user_v_id_azp_application];
			$var_role = $value[d_azp_user_v_id_azp_role];
		# Final del recorrido
		endforeach;
	}
?>
<?php if (false != $var_user_session): foreach ($var_user_session as $key_session): endforeach; endif; ?>
	<aside class="page-sidebar">
		<div class="page-logo">
			<a href="#" class="page-logo-link press-scale-down d-flex align-items-center position-relative" data-toggle="modal" data-target="#modal-shortcut">
				<img src="views/backend/images/logo.png" aria-roledescription="logo">
				<!--<img src="views/templates/smart/dist/img/logo.png" alt="SmartAdmin WebApp" aria-roledescription="logo">-->
				<!--<span class="page-logo-text mr-1"><?= APP; ?></span>-->
				<span class="position-absolute text-white opacity-50 small pos-top pos-right mr-2 mt-n2"></span>
				<i class="fal fa-angle-down d-inline-block ml-1 fs-lg color-primary-300"></i>
			</a>
		</div>
		<nav id="js-primary-nav" class="primary-nav" role="navigation">
			<div class="nav-filter">
				<div class="position-relative">
					<input type="text" id="nav_filter_input" placeholder="Filtrar Menu" class="form-control" tabindex="0">
					<a href="#" onclick="return false;" class="btn-primary btn-search-close js-waves-off"
					data-action="toggle" data-class="list-filter-active" data-target=".page-sidebar">
						<i class="fal fa-chevron-up"></i>
					</a>
				</div>
			</div>
			<div class="info-card">
				<a href="profile/">
					<!--<img src="views/templates/smart/dist/img/demo/avatars/avatar-admin.png" class="profile-image rounded-circle"-->
					<img src="views/backend/images/profile-user.png" class="profile-image rounded-circle"
					alt="<?= $key_session['lbl_azp_data_personal_t_names']; ?> <?= $key_session['lbl_azp_data_personal_t_surnames']; ?>">
				</a>
				<div class="info-card-text">
					<span class="d-inline-block text-truncate text-truncate-sm">
						Bienvenido Usuario!
					</span>
					<span class="d-inline-block text-truncate text-truncate-sm">
						User: <?= $key_session['lbl_azp_user_t_login']; ?>
					</span>
					<span class="d-inline-block text-truncate text-truncate-sm">
						Rol: <?= $key_session['lbl_azp_role_t_name']; ?>
					</span>
				</div>
				<!--<img src="views/backend/images/fondo.jpg" class="cover" alt="cover">-->
				<!--<img src="views/templates/smart/dist/img/card-backgrounds/cover-2-lg.png" class="cover" alt="cover">-->
				<a href="#" onclick="return false;" class="pull-trigger-btn" data-action="toggle"
				data-class="list-filter-active" data-target=".page-sidebar" data-focus="nav_filter_input">
					<i class="fal fa-angle-down"></i>
				</a>
			</div>
			<ul id="js-nav-menu" class="nav-menu">
				<?php if (false != $var_permits_menu_value): ?>
					<?php foreach ($var_permits_menu_value as $key_menu_value): ?>
						<li>
							<a href="<?= $key_menu_value['lbl_azp_menu_crud_t_url']; ?>info/"
							title="<?= $key_menu_value['lbl_azp_menu_crud_t_name']; ?>"
							data-filter-tags="<?= $key_menu_value['lbl_azp_menu_crud_t_name']; ?>">
								<i class="<?= $key_menu_value['lbl_azp_icon_code_t_name']; ?>"></i>
								<span class="nav-link-text" data-i18n="nav.<?= $key_menu_value['lbl_azp_menu_crud_t_name']; ?>">
									<?= $key_menu_value['lbl_azp_menu_crud_t_name']; ?>
								</span>
							</a>
						</li>
					<?php endforeach; ?>
				<?php endif; ?>
			</ul>
			<div class="filter-message js-filter-message bg-success-600"></div>
		</nav>
		<div class="nav-footer shadow-top">
			<a href="#" onclick="return false;" data-action="toggle" data-class="nav-function-minify" class="hidden-md-down">
				<i class="ni ni-chevron-right"></i>
				<i class="ni ni-chevron-right"></i>
			</a>
			<ul class="list-table m-auto nav-footer-buttons">
				<li>
					<a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Chat logs">
						<i class="fal fa-comments"></i>
					</a>
				</li>
				<li>
					<a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Support Chat">
						<i class="fal fa-life-ring"></i>
					</a>
				</li>
				<li>
					<a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Make a call">
						<i class="fal fa-phone"></i>
					</a>
				</li>
			</ul>
		</div>
	</aside>