<?php if (false != $var_config_ds_color): foreach ($var_config_ds_color as $cd_config_ds_color): endforeach; endif; ?>
<?php if (false != $var_config_ds_dimension): foreach ($var_config_ds_dimension as $cd_config_ds_dimension): endforeach; endif; ?>
<?php if (false != $var_config_ds_theme): foreach ($var_config_ds_theme as $cd_config_ds_theme): endforeach; endif; ?>

<?php if (false != $var_btn_action): foreach ($var_btn_action as $cd_btn_action): endforeach; endif; ?>
<?php if (false != $var_btn_cancel): foreach ($var_btn_cancel as $cd_btn_cancel): endforeach; endif; ?>
<?php if (false != $var_btn_change): foreach ($var_btn_change as $cd_btn_change): endforeach; endif; ?>
<?php if (false != $var_btn_close): foreach ($var_btn_close as $cd_btn_close): endforeach; endif; ?>
<?php if (false != $var_btn_column_toggle): foreach ($var_btn_column_toggle as $cd_btn_column_toggle): endforeach; endif; ?>
<?php if (false != $var_btn_colvis_column): foreach ($var_btn_colvis_column as $cd_btn_colvis_column): endforeach; endif; ?>
<?php if (false != $var_btn_colvis_restore): foreach ($var_btn_colvis_restore as $cd_btn_colvis_restore): endforeach; endif; ?>
<?php if (false != $var_btn_copy): foreach ($var_btn_copy as $cd_btn_copy): endforeach; endif; ?>
<?php if (false != $var_btn_create): foreach ($var_btn_create as $cd_btn_create): endforeach; endif; ?>
<?php if (false != $var_btn_csv): foreach ($var_btn_csv as $cd_btn_csv): endforeach; endif; ?>
<?php if (false != $var_btn_delete): foreach ($var_btn_delete as $cd_btn_delete): endforeach; endif; ?>
<?php if (false != $var_btn_detail): foreach ($var_btn_detail as $cd_btn_detail): endforeach; endif; ?>
<?php if (false != $var_btn_email): foreach ($var_btn_email as $cd_btn_email): endforeach; endif; ?>
<?php if (false != $var_btn_excel): foreach ($var_btn_excel as $cd_btn_excel): endforeach; endif; ?>
<?php if (false != $var_btn_export): foreach ($var_btn_export as $cd_btn_export): endforeach; endif; ?>
<?php if (false != $var_btn_file): foreach ($var_btn_file as $cd_btn_file): endforeach; endif; ?>
<?php if (false != $var_btn_import): foreach ($var_btn_import as $cd_btn_import): endforeach; endif; ?>
<?php if (false != $var_btn_menu): foreach ($var_btn_menu as $cd_btn_menu): endforeach; endif; ?>
<?php if (false != $var_btn_page_length): foreach ($var_btn_page_length as $cd_btn_page_length): endforeach; endif; ?>
<?php if (false != $var_btn_pdf): foreach ($var_btn_pdf as $cd_btn_pdf): endforeach; endif; ?>
<?php if (false != $var_btn_print): foreach ($var_btn_print as $cd_btn_print): endforeach; endif; ?>
<?php if (false != $var_btn_remove): foreach ($var_btn_remove as $cd_btn_remove): endforeach; endif; ?>
<?php if (false != $var_btn_report): foreach ($var_btn_report as $cd_btn_report): endforeach; endif; ?>
<?php if (false != $var_btn_restore): foreach ($var_btn_restore as $cd_btn_restore): endforeach; endif; ?>
<?php if (false != $var_btn_search): foreach ($var_btn_search as $cd_btn_search): endforeach; endif; ?>
<?php if (false != $var_btn_sub_menu): foreach ($var_btn_sub_menu as $cd_btn_sub_menu): endforeach; endif; ?>
<?php if (false != $var_btn_sync): foreach ($var_btn_sync as $cd_btn_sync): endforeach; endif; ?>
<?php if (false != $var_btn_template): foreach ($var_btn_template as $cd_btn_template): endforeach; endif; ?>
<?php if (false != $var_btn_update): foreach ($var_btn_update as $cd_btn_update): endforeach; endif; ?>
<?php if (false != $var_btn_visible): foreach ($var_btn_visible as $cd_btn_visible): endforeach; endif; ?>

<?php if (false != $var_table_by_create): foreach ($var_table_by_create as $cd_table_by_create): endforeach; endif; ?>
<?php if (false != $var_table_change): foreach ($var_table_change as $cd_table_change): endforeach; endif; ?>
<?php if (false != $var_table_detail): foreach ($var_table_detail as $cd_table_detail): endforeach; endif; ?>
<?php if (false != $var_table_eliminate): foreach ($var_table_eliminate as $cd_table_eliminate): endforeach; endif; ?>
<?php if (false != $var_table_read): foreach ($var_table_read as $cd_table_read): endforeach; endif; ?>
<?php if (false != $var_table_remove): foreach ($var_table_remove as $cd_table_remove): endforeach; endif; ?>

<?php if (false != $var_cm_md_change): foreach ($var_cm_md_change as $cm_md_change): endforeach; endif; ?>
<?php if (false != $var_cm_md_create): foreach ($var_cm_md_create as $cm_md_create): endforeach; endif; ?>
<?php if (false != $var_cm_md_delete): foreach ($var_cm_md_delete as $cm_md_delete): endforeach; endif; ?>
<?php if (false != $var_cm_md_detail): foreach ($var_cm_md_detail as $cm_md_detail): endforeach; endif; ?>
<?php if (false != $var_cm_md_email): foreach ($var_cm_md_email as $cm_md_email): endforeach; endif; ?>
<?php if (false != $var_cm_md_file): foreach ($var_cm_md_file as $cm_md_file): endforeach; endif; ?>
<?php if (false != $var_cm_md_import): foreach ($var_cm_md_import as $cm_md_import): endforeach; endif; ?>
<?php if (false != $var_cm_md_remove): foreach ($var_cm_md_remove as $cm_md_remove): endforeach; endif; ?>
<?php if (false != $var_cm_md_report): foreach ($var_cm_md_report as $cm_md_report): endforeach; endif; ?>
<?php if (false != $var_cm_md_restore): foreach ($var_cm_md_restore as $cm_md_restore): endforeach; endif; ?>
<?php if (false != $var_cm_md_sub_menu): foreach ($var_cm_md_sub_menu as $cm_md_sub_menu): endforeach; endif; ?>
<?php if (false != $var_cm_md_update): foreach ($var_cm_md_update as $cm_md_update): endforeach; endif; ?>

<?php if (false != $var_cp_pnl_change): foreach ($var_cp_pnl_change as $cp_pnl_change): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_create): foreach ($var_cp_pnl_create as $cp_pnl_create): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_delete): foreach ($var_cp_pnl_delete as $cp_pnl_delete): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_detail): foreach ($var_cp_pnl_detail as $cp_pnl_detail): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_email): foreach ($var_cp_pnl_email as $cp_pnl_email): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_file): foreach ($var_cp_pnl_file as $cp_pnl_file): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_import): foreach ($var_cp_pnl_import as $cp_pnl_import): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_remove): foreach ($var_cp_pnl_remove as $cp_pnl_remove): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_report): foreach ($var_cp_pnl_report as $cp_pnl_report): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_restore): foreach ($var_cp_pnl_restore as $cp_pnl_restore): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_sub_menu): foreach ($var_cp_pnl_sub_menu as $cp_pnl_sub_menu): endforeach; endif; ?>
<?php if (false != $var_cp_pnl_update): foreach ($var_cp_pnl_update as $cp_pnl_update): endforeach; endif; ?>

<?php if (false != $var_menu_crud_icon_code): foreach ($var_menu_crud_icon_code as $k_mc_ic): endforeach; endif; ?>

<?php $this->insert('backend/design/ds-main/file-start'); ?>
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
			<div id="panel-1" class="panel rounded-0">
				<div class="panel-container show">
					<div class="panel-content p-0">
						<div class="panel-tag p-2 bg-white">
							<ol class="breadcrumb page-breadcrumb">
								<li class="breadcrumb-item text-danger">
									<a href="dashboard/" class="text-contrast">
										<em class="far fa-tachometer-alt-average text-primary"></em>
										<span class="text-dark">Dashboard</span>
									</a>
								</li>
								<li class="breadcrumb-item text-danger">
									<a href="<?= $k_mc_ic['lbl_azp_menu_crud_t_url']; ?>info/">
										<em class="<?= $k_mc_ic['lbl_azp_icon_code_t_name']; ?>"></em>
										<span class="text-dark"><?= $k_mc_ic['lbl_azp_menu_crud_t_name']; ?></span>
									</a>
								</li>
								<li class="position-absolute pos-top pos-right d-none d-sm-block text-dark">
									<span class="js-get-date"></span>
								</li>
							</ol>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
			<?php if ($k_mc_ic['lbl_azp_menu_crud_m_description'] != '' || $k_mc_ic['lbl_azp_menu_crud_m_description'] != NULL): ?>
				<div class="alert alert-info alert-dismissible fade show p-2 rounded-0 mb-4" role="alert">
					<div class="d-flex align-items-center">
						<div class="alert-icon width-2">
							<span class="icon-stack" style="font-size: 20px;">
								<i class="base-2 icon-stack-3x color-primary-400"></i>
								<i class="base-10 text-white icon-stack-1x"></i>
								<i class="ni md-profile color-primary-800 icon-stack-2x"></i>
							</span>
						</div>
						<div class="flex-1">
							<strong>Acerca De:</strong>
							<span><?= $k_mc_ic['lbl_azp_menu_crud_m_description']; ?></span>
						</div>
					</div>
				</div>
			<?php endif; ?>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
			<div id="panel-1" class="panel">
				<div class="panel-hdr bg-dark text-white rounded-0">
					<h2 class="text-white">
						<span class="icon-stack fs-xxl mr-2">
							<i class="base base-7 icon-stack-3x opacity-100 color-primary-500"></i>
							<i class="base base-7 icon-stack-2x opacity-100 color-primary-300"></i>
							<i class="<?= $k_mc_ic['lbl_azp_icon_code_t_name']; ?> icon-stack-1x opacity-100 fa-spin"></i>
						</span>
						<span><?= $k_mc_ic['lbl_azp_menu_crud_t_name']; ?></span>
					</h2>
					<div class="panel-toolbar">
						<button class="btn btn-panel btn-primary" title="Informacion" data-toggle="modal"
						data-target=".modal-div-info" data-offset="0,10" data-original-title="Informacion"></button>
						<!--<button class="btn btn-panel btn-warning" data-action="panel-fullscreen"
						data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>-->
					</div>
				</div>
				<div class="panel-container show">
					<div class="panel-content p-1">
						<?php $this->insert('backend/design/ds-main/read-field'); ?>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
								<div class="form-group">
									<div class="btn-group" role="group">
										<?php if (false != $var_permits_btn_search): ?>
											<div class="input-group-append mr-1">
												<button type="button" class="btn btn-sm <?= $cd_btn_search[d_azp_configuration_button_t_name]; ?>"
												title="Buscador" tabindex="0" aria-controls="dt_user" data-toggle="modal" data-target=".modal-div-filter-column">
													<em class="far fa-search"></em>
												</button>
											</div>
										<?php endif; ?>
										<?php if (false != $var_permits_btn_action): ?>
											<div class="input-group-append mr-1" id="div_info_data">
												<button type="button" class="btn btn-sm <?= $cd_btn_action[d_azp_configuration_button_t_name]; ?>"
												data-template='<div class="tooltip" role="tooltip"><div class="tooltip-inner bg-primary-500"></div></div>'
												data-toggle="tooltip" data-original-title="Acciones" onclick="event_info_data();">
													<em class="far fa-cog"></em>
												</button>
											</div>
										<?php endif; ?>
										<?php if (false != $var_permits_btn_action): ?>
											<div class="d-none input-group-append mr-1" id="div_info_remove">
												<button type="button" class="btn btn-sm <?= $cd_btn_action[d_azp_configuration_button_t_name]; ?>"
												data-template='<div class="tooltip" role="tooltip"><div class="tooltip-inner bg-primary-500"></div></div>'
												data-toggle="tooltip" data-original-title="Acciones" onclick="event_info_remove();">
													<em class="far fa-cog"></em>
												</button>
											</div>
										<?php endif; ?>
										<?php if (false != $var_permits_btn_action): ?>
											<div class="d-none input-group-append mr-1" id="div_info_eliminate">
												<button type="button" class="btn btn-sm <?= $cd_btn_action[d_azp_configuration_button_t_name]; ?>"
												data-template='<div class="tooltip" role="tooltip"><div class="tooltip-inner bg-primary-500"></div></div>'
												data-toggle="tooltip" data-original-title="Acciones" onclick="event_info_eliminate();">
													<em class="far fa-cog"></em>
												</button>
											</div>
										<?php endif; ?>
										<?php if (false != $var_permits_btn_export): ?>
											<div class="input-group-append mr-1">
												<button type="button" class="btn btn-sm <?= $cd_btn_export[d_azp_configuration_button_t_name]; ?>"
												data-template='<div class="tooltip" role="tooltip"><div class="tooltip-inner bg-primary-500"></div></div>'
												data-toggle="tooltip" data-original-title="Exportar" onclick="event_info_export();">
													<em class="far fa-file-export"></em>
												</button>
											</div>
										<?php endif; ?>
										<?php if (false != $var_permits_btn_visible): ?>
											<div class="input-group-append mr-1">
												<button type="button" class="btn btn-sm <?= $cd_btn_visible[d_azp_configuration_button_t_name]; ?>"
												data-template='<div class="tooltip" role="tooltip"><div class="tooltip-inner bg-primary-500"></div></div>'
												data-toggle="tooltip" data-original-title="Visibilidad" onclick="event_info_visible();">
													<em class="far fa-low-vision"></em>
												</button>
											</div>
										<?php endif; ?>
										<div class="input-group input-group-sm">
											<select name="field_ft_data" id="field_ft_data" class="custom-select form-control border-success"
											required="" onchange="event_data_info();" onclick="event_data_class();">
												<?php if (false != $var_permits_data_read): ?>
													<option value="1">Registros</option>
												<?php endif; ?>
												<?php if (false != $var_permits_data_by_create): ?>
													<option value="2">Creados Por Mi</option>
												<?php endif; ?>
												<?php if (false != $var_permits_data_remove): ?>
													<option value="3">Removidos</option>
												<?php endif; ?>
												<?php if (false != $var_permits_data_eliminate): ?>
													<option value="4">Eliminados</option>
												<?php endif; ?>
											</select>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="table-responsive">
							<table id="dt_info" class="text-center table table-bordered table-sm table-hover table-striped w-100 nowrap" cellspacing="0" width="100%">
								<thead class="<?= $cd_table_read[d_azp_configuration_table_t_name]; ?>"></thead>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-info" class="modal fade modal-div-info"
	data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;">
		<div class="modal-dialog modal-dialog-scrollable modal-sm modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-header bg-dark text-white">
					<h5 class="modal-title text-white">Informacion</h5>
					<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true"><i class="far fa-times"></i></span>
					</button>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<div class="panel-tag">
								<p class="text-center text-contrast">
									<span class="text-dark">
										El manejo de datos de una interfaz a menudo es parte clave de una aplicación compleja, por eso te brindamos y proporcionamos dentro de la plataforma funcionalidades completas que te brindan una mayor experiencia con la interactividad de nuestro sistema a traves de nuestro portal o aplicacion web.
									</span>
								</p>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-sm waves-effect waves-light <?= $cd_btn_cancel[d_azp_configuration_button_t_name]; ?>" data-dismiss="modal">
						<em class="far fa-times-circle"></em>
						<span>Cerrar</span>
					</button>
				</div>
			</div>
		</div>
	</div>

	<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-filter-column"
	data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;"
	class="modal fade <?php if ($cm_md_report['lbl_mc'] == 'modal-fullscreen'): echo 'modal-fullscreen'; endif; ?> modal-div-filter-column">
		<div class="<?php if ($cm_md_report['lbl_mc'] != 'modal-fullscreen'): echo $cm_md_report['lbl_mc'];
		else: echo 'modal-dialog modal-dialog-scrollable modal-dialog-centered'; endif; ?>">
			<div class="modal-content">
				<div class="modal-header <?php if ($cm_md_report['lbl_md'] == 3): else: echo $cp_pnl_report['lbl_pnl']; ?> text-white<?php endif; ?>">
					<h5 class="modal-title text-white text-center">Filtrar Columnas</h5>
					<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true"><i class="far fa-times"></i></span>
					</button>
				</div>
				<div class="modal-body">
					<ul class="nav nav-tabs border-bottom-0 nav-tabs-clean" role="tablist">
						<li class="nav-item" data-toggle="popover" data-trigger="hover" data-placement="top" title="" data-original-title="Principales"
						data-content="Informacion de los datos almancenados del registro en la base de datos.">
							<a class="nav-link active p-3" data-toggle="tab" href="#tab-justified-fc-1" role="tab">
								<i class="far fa-table text-success"></i>
								<span class="hidden-sm-down ml-1">Principales</span>
							</a>
						</li>
						<li class="nav-item" data-toggle="popover" data-trigger="hover" data-placement="top" title="" data-original-title="Auditoria"
						data-content="Informacion de los datos almancenados del registro en la base de datos.">
							<a class="nav-link p-3" data-toggle="tab" href="#tab-justified-fc-2" role="tab">
								<i class="far fa-table text-success"></i>
								<span class="hidden-sm-down ml-1">Auditoria</span>
							</a>
						</li>
					</ul>
					<div class="tab-content p-3">
						<div class="tab-pane fade show active" id="tab-justified-fc-1" role="tabpanel">
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
									<div class="table-responsive">
										<table class="text-center table table-bordered table-sm table-hover table-striped w-100 nowrap" cellspacing="0" width="100%">
											<thead>
												<tr>
													<th>Columnas</th>
													<th class="d-none">Regex</th>
													<th class="d-none">Inteligente</th>
												</tr>
											</thead>
											<tbody>
												<?php for ($i = 7; $i <= 7; $i++) { ?>
													<tr id="filter_col_<?= $i; ?>" data-column="<?= $i; ?>">
														<td>
															<div class="input-group input-group-sm">
																<input type="text" class="form-control column_filter" id="col_<?= $i; ?>_filter" placeholder="">
															</div>
														</td>
														<td class="d-none">
															<div class="custom-control custom-checkbox">
																<input type="checkbox" class="custom-control-input column_filter" id="col_<?= $i; ?>_regex" checked="">
																<label class="custom-control-label" for="col_<?= $i; ?>_regex"></label>
															</div>
														</td>
														<td class="d-none">
															<div class="custom-control custom-checkbox">
																<input type="checkbox" class="custom-control-input column_filter" id="col_<?= $i; ?>_smart" checked="">
																<label class="custom-control-label" for="col_<?= $i; ?>_smart"></label>
															</div>
														</td>
													</tr>
												<?php } ?>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
						<div class="tab-pane fade" id="tab-justified-fc-2" role="tabpanel">
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
									<div class="table-responsive">
										<table class="text-center table table-bordered table-sm table-hover table-striped w-100 nowrap" cellspacing="0" width="100%">
											<thead>
												<tr>
													<th>Columnas</th>
													<th class="d-none">Regex</th>
													<th class="d-none">Inteligente</th>
												</tr>
											</thead>
											<tbody>
												<?php for ($i = 0; $i <= 6; $i++) { ?>
													<tr id="filter_col_<?= $i; ?>" data-column="<?= $i; ?>">
														<td>
															<div class="input-group input-group-sm">
																<input type="text" class="form-control column_filter" id="col_<?= $i; ?>_filter" placeholder="">
															</div>
														</td>
														<td class="d-none">
															<div class="custom-control custom-checkbox">
																<input type="checkbox" class="custom-control-input column_filter" id="col_<?= $i; ?>_regex" checked="">
																<label class="custom-control-label" for="col_<?= $i; ?>_regex"></label>
															</div>
														</td>
														<td class="d-none">
															<div class="custom-control custom-checkbox">
																<input type="checkbox" class="custom-control-input column_filter" id="col_<?= $i; ?>_smart" checked="">
																<label class="custom-control-label" for="col_<?= $i; ?>_smart"></label>
															</div>
														</td>
													</tr>
												<?php } ?>
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-sm waves-effect waves-light <?= $cd_btn_cancel[d_azp_configuration_button_t_name]; ?>" data-dismiss="modal">
						<em class="far fa-times-circle"></em>
						<span>Cerrar</span>
					</button>
				</div>
			</div>
		</div>
	</div>

	<?php if (false != $var_permits_value_change): ?>
		<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-change"
		data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;"
		class="modal fade <?php if ($cm_md_change['lbl_mc'] == 'modal-fullscreen'): echo 'modal-fullscreen'; endif; ?> modal-div-change">
			<div class="<?php if ($cm_md_change['lbl_mc'] != 'modal-fullscreen'): echo $cm_md_change['lbl_mc'];
			else: echo 'modal-dialog modal-dialog-scrollable modal-dialog-centered'; endif; ?>">
				<div class="modal-content">
					<div class="modal-header <?php if ($cm_md_change['lbl_md'] == 3): else: echo $cp_pnl_change['lbl_pnl']; ?> text-white<?php endif; ?>">
						<h5 class="modal-title text-white">Control De Cambios</h5>
						<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true"><i class="far fa-times"></i></span>
						</button>
					</div>
					<div class="modal-body">
						<div class="table-responsive">
							<table id="dt_change" class="text-center table table-bordered table-sm table-hover table-striped w-100 nowrap" cellspacing="0" width="100%">
								<thead class="<?= $cd_table_change[d_azp_configuration_table_t_name]; ?>"></thead>
							</table>
						</div>
					</div>
					<div class="modal-footer">
						<div class="btn-group" role="group">
							<?php if (false != $var_permits_btn_action): ?>
								<div class="input-group-append mr-1">
									<button type="button" class="btn btn-sm <?= $cd_btn_action[d_azp_configuration_button_t_name]; ?>"
									data-template='<div class="tooltip" role="tooltip"><div class="tooltip-inner bg-primary-500"></div></div>'
									data-toggle="tooltip" data-original-title="Acciones" onclick="event_change_action();">
										<em class="far fa-cog"></em>
									</button>
								</div>
							<?php endif; ?>
							<?php if (false != $var_permits_btn_export): ?>
								<div class="input-group-append mr-1">
									<button type="button" class="btn btn-sm <?= $cd_btn_export[d_azp_configuration_button_t_name]; ?>"
									data-template='<div class="tooltip" role="tooltip"><div class="tooltip-inner bg-primary-500"></div></div>'
									data-toggle="tooltip" data-original-title="Exportar" onclick="event_change_export();">
										<em class="far fa-file-export"></em>
									</button>
								</div>
							<?php endif; ?>
							<?php if (false != $var_permits_btn_visible): ?>
								<div class="input-group-append mr-1">
									<button type="button" class="btn btn-sm <?= $cd_btn_visible[d_azp_configuration_button_t_name]; ?>"
									data-template='<div class="tooltip" role="tooltip"><div class="tooltip-inner bg-primary-500"></div></div>'
									data-toggle="tooltip" data-original-title="Visible" onclick="event_change_visible();">
										<em class="far fa-low-vision"></em>
									</button>
								</div>
							<?php endif; ?>
							<?php if (false != $var_permits_value_close): ?>
								<button type="button" data-dismiss="modal"
								class="btn btn-sm waves-effect waves-light <?= $cd_btn_close[d_azp_configuration_button_t_name]; ?>">
									<em class="far fa-times-circle"></em>
									<span>Cerrar</span>
								</button>
							<?php endif; ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	<?php endif; ?>

	<?php if (false != $var_permits_value_detail): ?>
		<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-detail"
		data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;"
		class="modal fade <?php if ($cm_md_detail['lbl_mc'] == 'modal-fullscreen'): echo 'modal-fullscreen'; endif; ?> modal-div-detail">
			<div class="<?php if ($cm_md_detail['lbl_mc'] != 'modal-fullscreen'): echo $cm_md_detail['lbl_mc'];
			else: echo 'modal-dialog modal-dialog-scrollable modal-dialog-centered'; endif; ?>">
				<div class="modal-content">
					<div class="modal-header <?php if ($cm_md_detail['lbl_md'] == 3): else: echo $cp_pnl_detail['lbl_pnl']; ?> text-white<?php endif; ?>">
						<h5 class="modal-title text-white">Detalles Del Registro</h5>
						<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true"><i class="far fa-times"></i></span>
						</button>
					</div>
					<div class="modal-body">
						<ul class="nav nav-tabs border-bottom-0 nav-tabs-clean" role="tablist">
							<li class="nav-item" data-toggle="popover" data-trigger="hover" data-placement="top" title="" data-original-title="Datos Principales"
							data-content="Informacion de los datos almancenados del registro en la base de datos.">
								<a class="nav-link active p-3" data-toggle="tab" href="#tab-justified-dt-1" role="tab">
									<i class="far fa-table text-success"></i>
									<span class="hidden-sm-down ml-1">Datos Principales</span>
								</a>
							</li>
							<li class="nav-item" data-toggle="popover" data-trigger="hover" data-placement="top" title="" data-original-title="Auditoria"
							data-content="Informacion de los datos almancenados del registro en la base de datos.">
								<a class="nav-link p-3" data-toggle="tab" href="#tab-justified-dt-2" role="tab">
									<i class="far fa-table text-success"></i>
									<span class="hidden-sm-down ml-1">Auditoria</span>
								</a>
							</li>
						</ul>
						<div class="tab-content p-3">
							<div class="tab-pane fade show active" id="tab-justified-dt-1" role="tabpanel">
								<div class="table-responsive">
									<table class="text-center table table-bordered table-sm table-hover table-striped w-100 nowrap">
										<thead class="<?= $cd_table_detail[d_azp_configuration_table_t_name]; ?>">
											<tr>
												<th>Definicion</th>
												<th>Resultado</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td>Nombre:</td>
												<td id="lbl_azp_sys_temp_t_name"></td>
											</tr>
											<tr>
												<td>Valor:</td>
												<td id="lbl_azp_sys_temp_t_value"></td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
							<div class="tab-pane fade" id="tab-justified-dt-2" role="tabpanel">
								<div class="table-responsive">
									<table class="text-center table table-bordered table-sm table-hover table-striped w-100 nowrap">
										<thead class="<?= $cd_table_detail[d_azp_configuration_table_t_name]; ?>">
											<tr>
												<th>Definicion</th>
												<th>Resultado</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td>Id:</td>
												<td id="lbl_azp_sys_temp_id_azp_sys_temp"></td>
											</tr>
											<tr>
												<td>Creado Por:</td>
												<td id="lbl_azp_user_t_login_created"></td>
											</tr>
											<tr>
												<td>Modificado Por:</td>
												<td id="lbl_azp_user_t_login_modified"></td>
											</tr>
											<tr>
												<td>Fecha Creacion:</td>
												<td id="lbl_azp_sys_temp_m_date_created"></td>
											</tr>
											<tr>
												<td>Fecha Modificacion:</td>
												<td id="lbl_azp_sys_temp_m_date_modified"></td>
											</tr>
											<tr>
												<td>Descripcion:</td>
												<td id="lbl_azp_sys_temp_m_description"></td>
											</tr>
											<tr>
												<td>Estado:</td>
												<td id="lbl_azp_sys_state_t_name"></td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-sm waves-effect waves-light <?= $cd_btn_cancel[d_azp_configuration_button_t_name]; ?>" data-dismiss="modal">
							<em class="far fa-times-circle"></em>
							<span>Cerrar</span>
						</button>
					</div>
				</div>
			</div>
		</div>
	<?php endif; ?>

	<?php if (false != $var_permits_value_report): ?>
		<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-report"
		data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;"
		class="modal fade <?php if ($cm_md_report['lbl_mc'] == 'modal-fullscreen'): echo 'modal-fullscreen'; endif; ?> modal-div-report">
			<div class="<?php if ($cm_md_report['lbl_mc'] != 'modal-fullscreen'): echo $cm_md_report['lbl_mc'];
			else: echo 'modal-dialog modal-dialog-scrollable modal-dialog-centered'; endif; ?>">
				<div class="modal-content">
					<div class="modal-header <?php if ($cm_md_report['lbl_md'] == 3): else: echo $cp_pnl_report['lbl_pnl']; ?> text-white<?php endif; ?>">
						<h5 class="modal-title text-white text-center">Reportes Graficos</h5>
						<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true"><i class="far fa-times"></i></span>
						</button>
					</div>
					<div class="modal-footer">
						
						<button type="button" class="btn btn-sm waves-effect waves-light <?= $cd_btn_cancel[d_azp_configuration_button_t_name]; ?>" data-dismiss="modal">
							<em class="far fa-times-circle"></em>
							<span>Cerrar</span>
						</button>
					</div>
				</div>
			</div>
		</div>
	<?php endif; ?>

	<?php if (false != $var_permits_value_sub_menu): ?>
		<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-sub-menu"
		data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;"
		class="modal fade <?php if ($cm_md_sub_menu['lbl_mc'] == 'modal-fullscreen'): echo 'modal-fullscreen'; endif; ?> modal-div-sub-menu">
			<div class="<?php if ($cm_md_sub_menu['lbl_mc'] != 'modal-fullscreen'): echo $cm_md_sub_menu['lbl_mc'];
			else: echo 'modal-dialog modal-dialog-scrollable modal-dialog-centered'; endif; ?>">
				<div class="modal-content">
					<div class="modal-header <?php if ($cm_md_sub_menu['lbl_md'] == 3): else: echo $cp_pnl_sub_menu['lbl_pnl']; ?> text-white<?php endif; ?>">
						<h5 class="modal-title text-white text-center">Sub Menu</h5>
						<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true"><i class="far fa-times"></i></span>
						</button>
					</div>
					<div class="modal-body">
						<?php foreach ($var_sub_menu_crud_order_by as $key_sub_menu_crud): ?>
							<a href="<?= $key_sub_menu_crud['lbl_azp_menu_crud_t_url']; ?>"
							class="btn btn-sm btn-block waves-effect waves-light <?= $cd_btn_menu[d_azp_configuration_button_t_name]; ?>">
								<em class="<?= $key_sub_menu_crud['lbl_azp_icon_code_t_name']; ?>"></em>
								<span><?= $key_sub_menu_crud['lbl_azp_menu_crud_t_name']; ?></span>
							</a>
						<?php endforeach; ?>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-sm waves-effect waves-light <?= $cd_btn_cancel[d_azp_configuration_button_t_name]; ?>" data-dismiss="modal">
							<em class="far fa-times-circle"></em>
							<span>Cerrar</span>
						</button>
					</div>
				</div>
			</div>
		</div>
	<?php endif; ?>

	<?php if (false != $var_permits_value_create): ?>
		<form class="form-horizontal needs-validation was-validated" novalidate="" role="form" enctype="application/x-www-form-urlencoded" id="form_create">
			<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-create"
			data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;"
			class="modal fade <?php if ($cm_md_create['lbl_mc'] == 'modal-fullscreen'): echo 'modal-fullscreen'; endif; ?> modal-div-create">
				<div class="<?php if ($cm_md_create['lbl_mc'] != 'modal-fullscreen'): echo $cm_md_create['lbl_mc'];
				else: echo 'modal-dialog modal-dialog-scrollable modal-dialog-centered'; endif; ?>">
					<div class="modal-content">
						<div class="modal-header <?php if ($cm_md_create['lbl_md'] == 3): else: echo $cp_pnl_create['lbl_pnl']; ?> text-white<?php endif; ?>">
							<h5 class="modal-title text-white">Nuevo Registro</h5>
							<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true"><i class="far fa-times"></i></span>
							</button>
						</div>
						<div class="modal-body">
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
									<div class="hide" id="form_ajax_create"></div>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 mb-3">
									<div class="form-group">
										<label for="field_cr_name" class="form-label <?php if ($cm_md_create['lbl_md'] == 3): ?>text-white<?php endif; ?>">
											<span>Nombre:</span>
											<span class="text-danger">*</span>
										</label>
										<div class="input-group input-group-sm">
											<input type="text" name="field_cr_name" id="field_cr_name" class="form-control" placeholder="Digita el texto ..." required="">
											<div class="invalid-feedback">
												<span>Digita un valor en el campo.</span>
											</div>
										</div>
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 mb-3">
									<div class="form-group">
										<label for="field_cr_value" class="form-label <?php if ($cm_md_create['lbl_md'] == 3): ?>text-white<?php endif; ?>">
											<span>Valor:</span>
											<span class="text-danger">*</span>
										</label>
										<div class="input-group input-group-sm">
											<input type="text" name="field_cr_value" id="field_cr_value" class="form-control" placeholder="Digita el texto ..." required="">
											<div class="invalid-feedback">
												<span>Digita un valor en el campo.</span>
											</div>
										</div>
									</div>
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
									<div class="form-group">
										<label for="field_cr_description" class="form-label <?php if ($cm_md_create['lbl_md'] == 3): ?>text-white<?php endif; ?>">
											<span>Descripcion:</span>
										</label>
										<div class="input-group input-group-sm">
											<textarea name="field_cr_description" id="field_cr_description" class="form-control" placeholder="Digita el texto ..." rows="5"></textarea>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" id="form_btn_create"
							class="btn btn-sm waves-effect waves-light <?= $cd_btn_create[d_azp_configuration_button_t_name]; ?>">
								<em class="far fa-save"></em>
								<span>Guardar</span>
							</button>
							<button type="button" class="btn btn-sm waves-effect waves-light <?= $cd_btn_cancel[d_azp_configuration_button_t_name]; ?>" data-dismiss="modal">
								<em class="far fa-times-circle"></em>
								<span>Cerrar</span>
							</button>
						</div>
					</div>
				</div>
			</div>
		</form>
	<?php endif; ?>

	<?php if (false != $var_permits_value_delete): ?>
		<form class="form-horizontal" role="form" enctype="application/x-www-form-urlencoded" id="form_delete">
			<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-delete"
			data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;"
			class="modal fade <?php if ($cm_md_delete['lbl_mc'] == 'modal-fullscreen'): echo 'modal-fullscreen'; endif; ?> modal-div-delete">
				<div class="<?php if ($cm_md_delete['lbl_mc'] != 'modal-fullscreen'): echo $cm_md_delete['lbl_mc'];
				else: echo 'modal-dialog modal-dialog-scrollable modal-dialog-centered'; endif; ?>">
					<div class="modal-content">
						<div class="modal-header <?php if ($cm_md_delete['lbl_md'] == 3): else: echo $cp_pnl_delete['lbl_pnl']; ?> text-white<?php endif; ?>">
							<h5 class="modal-title text-white">Eliminar Registro</h5>
							<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true"><i class="far fa-times"></i></span>
							</button>
						</div>
						<div class="modal-body">
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
									<div class="hide" id="form_ajax_delete"></div>
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<div class="form-group">
										<div class="input-group input-group-sm">
											<span>¿Estas seguro de eliminar el registro?</span>
											<input type="hidden" name="field_id_delete" id="field_id_delete" class="form-control" placeholder="Digita el texto ..." required="" readonly="">
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" id="form_btn_delete" onclick="event_delete();"
							class="btn btn-sm waves-effect waves-light <?= $cd_btn_delete[d_azp_configuration_button_t_name]; ?>">
								<em class="far fa-trash-alt"></em>
								<span>Eliminar</span>
							</button>
							<button type="button" class="btn btn-sm waves-effect waves-light <?= $cd_btn_cancel[d_azp_configuration_button_t_name]; ?>" data-dismiss="modal">
								<em class="far fa-times-circle"></em>
								<span>Cerrar</span>
							</button>
						</div>
					</div>
				</div>
			</div>
		</form>
	<?php endif; ?>

	<?php if (false != $var_permits_value_remove): ?>
		<form class="form-horizontal" role="form" enctype="application/x-www-form-urlencoded" id="form_remove">
			<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-remove"
			data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;"
			class="modal fade <?php if ($cm_md_remove['lbl_mc'] == 'modal-fullscreen'): echo 'modal-fullscreen'; endif; ?> modal-div-remove">
				<div class="<?php if ($cm_md_remove['lbl_mc'] != 'modal-fullscreen'): echo $cm_md_remove['lbl_mc'];
				else: echo 'modal-dialog modal-dialog-scrollable modal-dialog-centered'; endif; ?>">
					<div class="modal-content">
						<div class="modal-header <?php if ($cm_md_remove['lbl_md'] == 3): else: echo $cp_pnl_remove['lbl_pnl']; ?> text-white<?php endif; ?>">
							<h5 class="modal-title text-white">Remover Registro</h5>
							<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true"><i class="far fa-times"></i></span>
							</button>
						</div>
						<div class="modal-body">
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
									<div class="hide" id="form_ajax_remove"></div>
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<div class="form-group">
										<div class="input-group input-group-sm">
											<span>¿Estas seguro de remover el registro?</span>
											<input type="hidden" name="field_id_remove" id="field_id_remove" class="form-control" placeholder="Digita el texto ..." required="" readonly="">
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" id="form_btn_remove" onclick="event_remove();"
							class="btn btn-sm waves-effect waves-light <?= $cd_btn_remove[d_azp_configuration_button_t_name]; ?>">
								<em class="far fa-trash"></em>
								<span>Remover</span>
							</button>
							<button type="button" class="btn btn-sm waves-effect waves-light <?= $cd_btn_cancel[d_azp_configuration_button_t_name]; ?>" data-dismiss="modal">
								<em class="far fa-times-circle"></em>
								<span>Cerrar</span>
							</button>
						</div>
					</div>
				</div>
			</div>
		</form>
	<?php endif; ?>

	<?php if (false != $var_permits_value_restore): ?>
		<form class="form-horizontal" role="form" enctype="application/x-www-form-urlencoded" id="form_restore">
			<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-restore"
			data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;"
			class="modal fade <?php if ($cm_md_restore['lbl_mc'] == 'modal-fullscreen'): echo 'modal-fullscreen'; endif; ?> modal-div-restore">
				<div class="<?php if ($cm_md_restore['lbl_mc'] != 'modal-fullscreen'): echo $cm_md_restore['lbl_mc'];
				else: echo 'modal-dialog modal-dialog-scrollable modal-dialog-centered'; endif; ?>">
					<div class="modal-content">
						<div class="modal-header <?php if ($cm_md_restore['lbl_md'] == 3): else: echo $cp_pnl_restore['lbl_pnl']; ?> text-white<?php endif; ?>">
							<h5 class="modal-title text-white">Restaurar Registro</h5>
							<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true"><i class="far fa-times"></i></span>
							</button>
						</div>
						<div class="modal-body">
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
									<div class="hide" id="form_ajax_restore"></div>
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<div class="form-group">
										<div class="input-group input-group-sm">
											<span>¿Estas seguro de restaurar el registro?</span>
											<input type="hidden" name="field_id_restore" id="field_id_restore" class="form-control" placeholder="Digita el texto ..." required="" readonly="">
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" id="form_btn_restore" onclick="event_restore();"
							class="btn btn-sm waves-effect waves-light <?= $cd_btn_restore[d_azp_configuration_button_t_name]; ?>">
								<em class="far fa-redo-alt"></em>
								<span>Restaurar</span>
							</button>
							<button type="button" class="btn btn-sm waves-effect waves-light <?= $cd_btn_cancel[d_azp_configuration_button_t_name]; ?>" data-dismiss="modal">
								<em class="far fa-times-circle"></em>
								<span>Cerrar</span>
							</button>
						</div>
					</div>
				</div>
			</div>
		</form>
	<?php endif; ?>

	<?php if (false != $var_permits_value_update): ?>
		<form class="form-horizontal needs-validation was-validated" novalidate="" role="form" enctype="application/x-www-form-urlencoded" id="form_update">
			<div tabindex="-1" role="dialog" aria-hidden="true" id="modal-id-update"
			data-keyboard="false" data-backdrop="static" aria-labelledby="myCenterModalLabel" style="display: none;"
			class="modal fade <?php if ($cm_md_update['lbl_mc'] == 'modal-fullscreen'): echo 'modal-fullscreen'; endif; ?> modal-div-update">
				<div class="<?php if ($cm_md_update['lbl_mc'] != 'modal-fullscreen'): echo $cm_md_update['lbl_mc'];
				else: echo 'modal-dialog modal-dialog-scrollable modal-dialog-centered'; endif; ?>">
					<div class="modal-content">
						<div class="modal-header <?php if ($cm_md_update['lbl_md'] == 3): else: echo $cp_pnl_update['lbl_pnl']; ?> text-white<?php endif; ?>">
							<h5 class="modal-title text-white">Actualizar Registro</h5>
							<button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true"><i class="far fa-times"></i></span>
							</button>
						</div>
						<div class="modal-body">
							<div class="row">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
									<div class="hide" id="form_ajax_update"></div>
									<div class="input-group input-group-sm">
										<input type="hidden" name="field_up_id" id="field_up_id" class="form-control" placeholder="Digita el texto ..." required="" readonly="">
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 mb-3">
									<div class="form-group">
										<label for="field_up_name" class="form-label <?php if ($cm_md_update['lbl_md'] == 3): ?>text-white<?php endif; ?>">
											<span>Nombre:</span>
											<span class="text-danger">*</span>
										</label>
										<div class="input-group input-group-sm">
											<input type="text" name="field_up_name" id="field_up_name" class="form-control" placeholder="Digita el texto ..." required="">
											<div class="invalid-feedback">
												<span>Digita un valor en el campo.</span>
											</div>
										</div>
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 mb-3">
									<div class="form-group">
										<label for="field_up_value" class="form-label <?php if ($cm_md_update['lbl_md'] == 3): ?>text-white<?php endif; ?>">
											<span>Valor:</span>
											<span class="text-danger">*</span>
										</label>
										<div class="input-group input-group-sm">
											<input type="number" name="field_up_value" id="field_up_value" class="form-control" placeholder="Digita el texto ..." required="">
											<div class="invalid-feedback">
												<span>Digita un valor en el campo.</span>
											</div>
										</div>
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-3 mb-3">
									<div class="form-group">
										<label for="field_up_state" class="form-label <?php if ($cm_md_update['lbl_md'] == 3): ?>text-white<?php endif; ?>">
											<span>Estado:</span>
											<span class="text-danger">*</span>
										</label>
										<div class="input-group input-group-sm">
											<select name="field_up_state" id="field_up_state" class="custom-select form-control" required="">
												<option value="">Seleccionar</option>
												<?php if (false != $var_sys_state_read): ?>
													<?php foreach ($var_sys_state_read as $key): ?>
														<option value="<?= $key['lbl_azp_sys_state_t_value']; ?>">
															<?= $key['lbl_azp_sys_state_t_name']; ?>
														</option>
													<?php endforeach; ?>
												<?php else: ?>
													<option value="">No existen resultados</option>
												<?php endif; ?>
											</select>
											<div class="invalid-feedback">
												<span>Selecciona un valor para el campo.</span>
											</div>
										</div>
									</div>
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
									<div class="form-group">
										<label for="field_up_description" class="form-label <?php if ($cm_md_update['lbl_md'] == 3): ?>text-white<?php endif; ?>">
											<span>Descripcion:</span>
										</label>
										<div class="input-group input-group-sm">
											<textarea name="field_up_description" id="field_up_description" class="form-control" placeholder="Digita el texto ..." rows="5"></textarea>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<button type="button" id="form_btn_update" onclick="event_update();"
							class="btn btn-sm waves-effect waves-light <?= $cd_btn_update[d_azp_configuration_button_t_name]; ?>">
								<em class="far fa-redo-alt"></em>
								<span>Actualizar</span>
							</button>
							<button type="button" class="btn btn-sm waves-effect waves-light <?= $cd_btn_cancel[d_azp_configuration_button_t_name]; ?>" data-dismiss="modal">
								<em class="far fa-times-circle"></em>
								<span>Cerrar</span>
							</button>
						</div>
					</div>
				</div>
			</div>
		</form>
	<?php endif; ?>
<?php $this->insert('backend/design/ds-main/file-end'); ?>

<script type="text/javascript">
	// Definicion del valor del controlador
	const var_controller = "<?= $df_var_controller; ?>";

	// Ejecutar funcion
	event_data_info();

	function event_data_info() {
		// Capturar el valor del campo de datos
		const ft_data = document.getElementById("field_ft_data").value;
		// Definir los valores
		const vdata = {
			'1': () => 'read/',
			'2': () => 'bycreate/',
			'3': () => 'remove/',
			'4': () => 'eliminate/',
		};
		// Valor por defecto de datos
		const vdefault = '1';
		// Valor obetnido para cargar datos de la url
		const url = vdata[ft_data] ? vdata[ft_data]() : vdefault;
		// Column Definitions
		var columnSet = [
			{
				title: "Id",
				id: "lbl_azp_sys_temp_id_azp_sys_temp",
				data: "lbl_azp_sys_temp_id_azp_sys_temp",
				type: "text",
				className: "text-dark",
				visible: true,
			},
			{
				title: "Creado Por",
				id: "lbl_azp_user_t_login_created",
				data: "lbl_azp_user_t_login_created",
				type: "text",
				className: "text-dark",
				visible: false,
			},
			{
				title: "Modificado Por",
				id: "lbl_azp_user_t_login_modified",
				data: "lbl_azp_user_t_login_modified",
				type: "text",
				className: "text-dark",
				visible: false,
			},
			{
				title: "Fecha Creacion",
				id: "lbl_azp_sys_temp_m_date_created",
				data: "lbl_azp_sys_temp_m_date_created",
				type: "text",
				className: "text-dark",
				visible: false,
			},
			{
				title: "Fecha Modificacion",
				id: "lbl_azp_sys_temp_m_date_modified",
				data: "lbl_azp_sys_temp_m_date_modified",
				type: "text",
				className: "text-dark",
				visible: false,
			},
			{
				title: "Descripcion",
				id: "lbl_azp_sys_temp_m_description",
				data: "lbl_azp_sys_temp_m_description",
				type: "text",
				className: "text-dark",
				visible: false,
			},
			{
				title: "Estado",
				id: "lbl_azp_sys_state_t_name",
				data: "lbl_azp_sys_state_t_name",
				type: "text",
				className: "text-dark",
				visible: false,
			},
			{
				title: "Nombre",
				id: "lbl_azp_sys_temp_t_name",
				data: "lbl_azp_sys_temp_t_name",
				type: "text",
				className: "text-dark",
				visible: true,
			},
		];
		// Inicializar tabla de datos
		var myTable = $('#dt_info').dataTable({
			// Reinicialiar los datos de la tabla
			destroy: true,
			// Estructura de las columnas para el DOOM
			dom: "<'row mb-3'<'col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 d-flex align-items-center'B>>"
				+ "<'row mb-3'<'col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 d-flex align-items-center justify-content-start'f>"
					+ "<'col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 d-flex align-items-center justify-content-end'l>>"
				+ "<'row mb-3'<'col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'tr>>"
				+ "<'row mb-3'<'col-xs-12 col-sm-12 col-md-5 col-lg-4 col-xl-4'i><'col-xs-12 col-sm-12 col-md-7 col-lg-8 col-xl-8'p>>",
			// Leer datos de prácticamente cualquier fuente de datos JSON
			ajax: "api<?= $df_var_controller; ?>" + url,
			// Cargar columnas del encabezado
			columns: columnSet,
			// Opciones para crear, editar, borrar y sincronizar
			altEditor: true,
			// Combinar valores en las demas celdas
			//autoFill: true,
			// Control de funciones Manejo inteligente del ancho de columna
			autoWidth: true,
			// Movilizar columnas en la tabla
			colReorder: true,
			// Creará todos los elementos HTML necesarios por adelantado
			deferRender: true,
			// Fijar columnas en la tabla
			fixedColumns: false,
			// Fijar columnas en la parte superior de la tabla
			fixedHeader: true,
			// Mostrar entradas de los registros
			info: true,
			// Focalizar una celda de la tabla
			//keys: true,
			// Cambiar numero de registros por pagina
			lengthChange: true,
			// Definir cantidad de registros por paginacion
			lengthMenu: [[100, 200, 300, 400, 500, 1000, 2000, 3000, 4000, 5000, -1,], [100, 200, 300, 400, 500, 1000, 2000, 3000, 4000, 5000, 'Todo',]],
			// Ordenar columnas en ascendente o descendente
			order: [[0, "asc",]],
			// Controlar si las tablas de datos deben usar celda única superior
			orderCellsTop: true,
			// Ordenar segun columna los registros
			ordering: true,
			// Paginar registros limitadamente
			paging: true,
			// Procesando informacion de registros
			processing: true,
			// Control para el tamaño de la tabla de datos
			//responsive: true,
			// Agrupar las filas de los registros
			//rowGroup: true,
			// Control de busqueda de registros
			searching: true,
			// Selccionar varias filas de registro
			select: 'single',
			// Procesamiento del lado del servidor
			//serverSide: true,
			// Permite dibujar grandes conjuntos de datos en la pantalla muy rápidamente
			//scroller: true,
			// Control para el desplazamiento medido de arriba abajo
			//scrollCollapse: true,
			// Control para el desplazamiento de derecha a izquiera
			scrollX: true,
			// Control para el desplazamiento medido de arriba abajo
			scrollY: 325,
			// Guardar el estado de una tabla (su posición de paginación, estado de pedido, etc.)
			stateSave: false,
			// Botones que usan clases de bootstrap
			buttons: [
				<?php if (false != $var_permits_value_sub_menu): ?>
					{
						text: '<i class="far fa-layer-group"></i>',
						titleAttr: 'Sub Menu',
						className: 'btn-sm <?= $cd_btn_sub_menu[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_sub_menu',
							'name': 'table_btn_sub_menu',
							'data-toggle': 'modal',
							'data-target': '.modal-div-sub-menu',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_report): ?>
					{
						text: '<i class="far fa-chart-bar"></i>',
						titleAttr: 'Reportes',
						className: 'btn-sm <?= $cd_btn_report[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_report',
							'name': 'table_btn_report',
							'data-toggle': 'modal',
							'data-target': '.modal-div-report',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_create): ?>
					{
						text: '<i class="far fa-plus"></i>',
						titleAttr: 'Nuevo',
						className: 'btn-sm <?= $cd_btn_create[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_create',
							'name': 'table_btn_create',
							'data-toggle': 'modal',
							'data-target': '.modal-div-create',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_update): ?>
					{
						text: '<i class="far fa-edit"></i>',
						titleAttr: 'Actualizar',
						className: 'btn-sm <?= $cd_btn_update[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_update',
							'name': 'table_btn_update',
							'onclick': 'modal_update();',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_restore): ?>
					{
						text: '<i class="far fa-redo-alt"></i>',
						titleAttr: 'Restaurar',
						className: 'd-none btn-sm <?= $cd_btn_restore[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_restore',
							'name': 'table_btn_restore',
							'onclick': 'modal_restore();',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_remove): ?>
					{
						text: '<i class="far fa-trash"></i>',
						titleAttr: 'Remover',
						className: 'btn-sm <?= $cd_btn_remove[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_remove',
							'name': 'table_btn_remove',
							'onclick': 'modal_remove();',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_delete): ?>
					{
						text: '<i class="far fa-trash-alt"></i>',
						titleAttr: 'Eliminar',
						className: 'd-none btn-sm <?= $cd_btn_delete[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_delete',
							'name': 'table_btn_delete',
							'onclick': 'modal_delete();',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_change): ?>
					{
						text: '<i class="far fa-exchange-alt"></i>',
						titleAttr: 'Cambios',
						className: 'btn-sm <?= $cd_btn_change[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_change',
							'name': 'table_btn_change',
							'onclick': 'event_change_data();',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_detail): ?>
					{
						text: '<i class="far fa-align-center"></i>',
						titleAttr: 'Detalles',
						className: 'btn-sm <?= $cd_btn_detail[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_detail',
							'name': 'table_btn_detail',
							'onclick': 'event_detail();',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_sync): ?>
					{
						text: '<i class="far fa-sync"></i>',
						titleAttr: 'Sincronizar',
						name: 'refresh',
						className: 'btn-sm <?= $cd_btn_sync[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_sync',
							'name': 'table_btn_sync',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_copy): ?>
					{
						extend: 'copyHtml5',
						text: '<i class="far fa-copy"></i>',
						titleAttr: 'Copiar',
						className: 'd-none btn-sm <?= $cd_btn_copy[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_copy',
							'name': 'table_btn_copy',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_pdf): ?>
					{
						extend: 'pdfHtml5',
						text: '<i class="far fa-file-pdf"></i>',
						titleAttr: 'PDF',
						className: 'd-none btn-sm <?= $cd_btn_pdf[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_pdf',
							'name': 'table_btn_pdf',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_excel): ?>
					{
						extend: 'excelHtml5',
						text: '<i class="far fa-file-excel"></i>',
						titleAttr: 'Excel',
						className: 'd-none btn-sm <?= $cd_btn_excel[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_excel',
							'name': 'table_btn_excel',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_csv): ?>
					{
						extend: 'csvHtml5',
						text: '<i class="far fa-file-csv"></i>',
						titleAttr: 'CSV',
						className: 'd-none btn-sm <?= $cd_btn_csv[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_csv',
							'name': 'table_btn_csv',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_print): ?>
					{
						autoPrint: true,
						extend: 'print',
						text: '<i class="far fa-print"></i>',
						titleAttr: 'Imprimir',
						className: 'd-none btn-sm <?= $cd_btn_print[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_print',
							'name': 'table_btn_print',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_column_toggle): ?>
					{
						columns: [1, 2, 3, 4, 5,],
						extend: 'columnToggle',
						text: '<i class="far fa-low-vision"></i>',
						titleAttr: 'Extender',
						className: 'd-none btn-sm <?= $cd_btn_column_toggle[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_column_toggle',
							'name': 'table_btn_column_toggle',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_colvis_restore): ?>
					{
						extend: 'colvisRestore',
						text: '<i class="far fa-low-vision"></i>',
						titleAttr: 'Restaurar',
						className: 'd-none btn-sm <?= $cd_btn_colvis_restore[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_colvis_restore',
							'name': 'table_btn_colvis_restore',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_colvis_column): ?>
					{
						extend: 'colvis',
						text: '<i class="far fa-low-vision"></i>',
						titleAttr: 'Visible',
						className: 'd-none btn-sm <?= $cd_btn_colvis_column[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_colvis_column',
							'name': 'table_btn_colvis_column',
						},
					},
				<?php endif; ?>
				<?php if (false != $var_permits_value_page_length): ?>
					{
						extend: 'pageLength',
						text: '<i class="far fa-database"></i>',
						titleAttr: 'Mostrar',
						className: 'd-none btn-sm <?= $cd_btn_page_length[d_azp_configuration_button_t_name]; ?>',
						attr: {
							'id': 'table_btn_page_length',
							'name': 'table_btn_page_length',
						},
					},
				<?php endif; ?>
			],
			columnDefs: [
				{
					targets: 6,
					render: function(data, type, full, meta) {
						var badge = {
							'Activo': {
								'title': 'Activo',
								'class': 'badge-success'
							},
							'Inactivo': {
								'title': 'Inactivo',
								'class': 'badge-warning'
							},
						};
						if (typeof badge[data] === 'undefined') { return data; }
						return '<span class="badge ' + badge[data].class + ' badge-pill">' + badge[data].title + '</span>';
					},
				},
			],
		});
		// Filtrar valores de los campos
		$('input.column_filter').on(
			'change click keyup', function () {
				event_filter_column(
					$(this).parents('tr').attr('data-column')
				);
			}
		);
		// Asingacion de valores e indices
		for (var i = 0; i <= 6; i++) {
			// Control de validacion existente
			if ($("#filter_col_" + i).length) {
				// Identificar el id del campo
				let input = document.getElementById("col_" + i + "_filter");
				// Asignacion de valor a la propiedad del input
				input.placeholder = columnSet[i]['title'];
				// Asignacion de valor a la propiedad del input
				input.type = columnSet[i]['type'];
			}
		}
		// Asingacion de valores e indices
		for (var i = 7; i <= columnSet.length - 1; i++) {
			// Control de validacion existente
			if ($("#filter_col_" + i).length) {
				let input = document.getElementById("col_" + i + "_filter");
				// Asignacion de valor a la propiedad del input
				input.placeholder = columnSet[i]['title'];
				// Asignacion de valor a la propiedad del input
				input.type = columnSet[i]['type'];
			}
		}
	}
</script>

<?php if (false != $var_menu_crud_script): foreach ($var_menu_crud_script as $key_mc_script): endforeach; endif; ?>
<script src="views/backend/scripts/inward/<?= $key_mc_script['lbl_azp_table_prefix_t_name']; ?>p_<?= $key_mc_script['lbl_azp_menu_crud_t_script']; ?>.js"></script>

</body>
</html>