<div class="page-content-overlay" data-action="toggle" data-class="mobile-nav-on"></div>
<footer class="page-footer" role="contentinfo">
	<div class="d-flex align-items-center flex-1 text-muted">
		<span class="hidden-md-down fw-700">
			<a href="<?= URL; ?>" class="text-primary fw-500" title="<?= URL; ?>">
				<?= APP; ?>
			</a> <span>2021 © Desarrollado Por BranderIdeas © Version 5.5</span>
		</span>
	</div>
	<div>
		<ul class="list-table m-0">
			<!--<li class="pl-3">
				<a href="privacy/" class="text-secondary fw-700">
					<span>Privacidad</span>
				</a>
			</li>-->
			<!--<li class="pl-3">
				<a href="license/" class="text-secondary fw-700">
					<span>Licencia</span>
				</a>
			</li>-->
			<!--<li class="pl-3">
				<a href="documentation/" class="text-secondary fw-700">
					<span>Documentacion</span>
				</a>
			</li>-->
			<!--<li class="pl-3 fs-xl">
				<a href="https://wrapbootstrap.com/user/MyOrange" class="text-secondary" target="_blank">
					<i class="fal fa-question-circle" aria-hidden="true"></i>
				</a>
			</li>-->
		</ul>
	</div>
</footer>