<?php if (DEBUG): ?><script src="views/app/js/jdev.js"></script><?php endif; ?>

<script src="views/templates/smart/dist/js/vendors.bundle.js"></script>
<script src="views/templates/smart/dist/js/app.bundle.js"></script>

<script type="text/javascript" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script src="views/templates/smart/dist/js/datagrid/datatables/datatables.bundle.js"></script>
<script src="views/templates/smart/dist/js/datagrid/datatables/datatables.export.js"></script>
<script src="views/templates/smart/dist/js/notifications/sweetalert2/sweetalert2.bundle.js"></script>
<script src="views/templates/smart/dist/js/formplugins/select2/select2.bundle.js"></script>
<script src="views/templates/smart/dist/js/statistics/easypiechart/easypiechart.bundle.js"></script>
<script src="views/templates/smart/dist/js/notifications/toastr/toastr.js"></script>
<script src="views/templates/smart/dist/js/statistics/chartjs/chartjs.bundle.js"></script>
<script src="views/templates/smart/dist/js/formplugins/inputmask/inputmask.bundle.js"></script>
<script src="views/templates/smart/dist/js/formplugins/bootstrap-colorpicker/bootstrap-colorpicker.js"></script>
<!--<script src="views/templates/smart/dist/js/formplugins/summernote/summernote.js"></script>-->

<script src="views/implement/summernote/summernote-bs4.min.js"></script>

<script src="views/backend/scripts/others/select2.js"></script>
<script src="views/backend/scripts/others/xlsx.js"></script>
<script src="views/backend/scripts/others/imask.js"></script>
<script src="views/backend/scripts/others/multiselect.min.js"></script>

<script src="views/backend/scripts/highcharts/highcharts.js"></script>
<script src="views/backend/scripts/highcharts/highcharts-more.js"></script>
<script src="views/backend/scripts/highcharts/modules/solid-gauge.js"></script>
<script src="views/backend/scripts/highcharts/modules/variable-pie.js"></script>
<script src="views/backend/scripts/highcharts/modules/series-label.js"></script>
<script src="views/backend/scripts/highcharts/modules/exporting.js"></script>
<script src="views/backend/scripts/highcharts/modules/export-data.js"></script>
<script src="views/backend/scripts/highcharts/modules/accessibility.js"></script>

<script src="views/backend/scripts/general/zv_azp_gsc_request.js"></script>
<script src="views/backend/scripts/general/zv_azp_ibn_control_panel.js"></script>
<script src="views/backend/scripts/general/zv_crt_binnacle.js"></script>
<script src="views/backend/scripts/general/zv_crt_client_phase.js"></script>
<script src="views/backend/scripts/general/zv_firm.js"></script>
<script src="views/backend/scripts/general/zv_gsc_follow_email.js"></script>
<script src="views/backend/scripts/general/zv_gsc_request.js"></script>
<script src="views/backend/scripts/general/zv_password.js"></script>
<script src="views/backend/scripts/general/zv_personal.js"></script>
<script src="views/backend/scripts/general/zv_profile.js"></script>
<script src="views/backend/scripts/general/zv_register_daily.js"></script>
<script src="views/backend/scripts/general/zv_register_full.js"></script>
<script src="views/backend/scripts/general/zv_setting_button.js"></script>
<script src="views/backend/scripts/general/zv_setting_design.js"></script>
<script src="views/backend/scripts/general/zv_setting_modal.js"></script>
<script src="views/backend/scripts/general/zv_setting_panel.js"></script>
<script src="views/backend/scripts/general/zv_setting_table.js"></script>
<script src="views/backend/scripts/general/zv_social_media.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.0.943/pdf.min.js">></script>

<script>$(document).ready(function() { $(":input").inputmask(); });</script>
<script type="text/javascript">
	function event_mask_date() {
		var inputElements = document.querySelectorAll("input[data-format]");
		inputElements.forEach(input => {
			let m = new IMask(input, {
				mask: input.getAttribute("data-format")
			});
		});
	};

	//$("#field_up_salary").inputmask("mask", { "currency": "$ 0.00" });

	/*var currencyMask = IMask(
		document.getElementById('field_up_salary'),
		{
			mask: '$ num',
			blocks: {
				num: {
					mask: Number,
					thousandsSeparator: '.'
				}
			}
		}
	);*/

	//data-inputmask="'alias': 'currency'"
</script>