<?php $this->insert('backend/design/ds-start/doctype'); ?>
<!--<body class="mod-bg-1 mod-nav-link header-function-fixed nav-function-fixed footer-function-fixed mod-clean-page-bg">-->
<!--<body class="mod-bg-1 mod-nav-link header-function-fixed nav-function-fixed footer-function-fixed mod-clean-page-bg mod-skin-dark">-->
<body class="mod-bg-1 mod-nav-link header-function-fixed nav-function-fixed footer-function-fixed mod-clean-page-bg nav-function-hidden">
<!--<body class="mod-bg-1 mod-nav-link header-function-fixed nav-function-fixed footer-function-fixed mod-clean-page-bg mod-skin-dark nav-function-hidden">-->
	<?php #$this->insert('backend/design/ds-start/script'); ?>
	<div class="page-wrapper">
		<div class="page-inner">
			<?php #$this->insert('backend/design/ds-start/sidebar'); ?>
			<div class="page-content-wrapper">
				<?php #$this->insert('backend/design/ds-start/header'); ?>
					<main id="js-page-content" role="main" class="page-content">
						<?php #$this->insert('backend/design/ds-start/content'); ?>