<!--<a href="#" class="back-to-top"><i class="ri-arrow-up-line"></i></a>-->
<script src="views/frontend/scripts/jquery-3.6.0.min.js"></script>
<script src="views/templates/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<!--<script src="views/templates/tempo/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>-->
<!--<script src="views/templates/tempo/vendor/jquery.easing/jquery.easing.min.js"></script>-->
<!--<script src="views/templates/tempo/vendor/php-email-form/validate.js"></script>-->
<!--<script src="views/templates/tempo/vendor/isotope-layout/isotope.pkgd.min.js"></script>-->
<!--<script src="views/templates/tempo/vendor/venobox/venobox.min.js"></script>-->
<!--<script src="views/templates/tempo/vendor/owl.carousel/owl.carousel.min.js"></script>-->
<!--<script src="views/templates/tempo/js/main.js"></script>-->
<!--<script src="views/app/js/jquery.numeric.js"></script>-->
<?php if (!isset($_SESSION[SESS_APP_ID])) { ?>
	<!--<script src="views/frontend/scripts/zz_contact.js"></script>-->
	<script src="views/frontend/scripts/zz_login.js"></script>
	<script src="views/frontend/scripts/zz_password.js"></script>
	<script src="views/frontend/scripts/zz_recover.js"></script>
	<!--<script src="views/frontend/scripts/zz_register.js"></script>-->
<?php } ?>
<!--<script>$('.numeric').numeric();</script>-->