<?php $this->insert('backend/design/ds-main/file-start'); ?>
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
			<div id="panel-1" class="panel rounded-0">
				<div class="panel-container show">
					<div class="panel-content p-0">
						<div class="panel-tag p-2 bg-white">
							<ol class="breadcrumb page-breadcrumb">
								<li class="breadcrumb-item text-danger">
									<a href="dashboard/" class="text-contrast">
										<em class="far fa-tachometer-alt-average text-primary"></em>
										<span class="text-dark">Dashboard</span>
									</a>
								</li>
								<li class="breadcrumb-item text-danger">
									<a href="crtclient/" class="text-contrast">
										<em class="far fa-tachometer-alt-average text-primary"></em>
										<span class="text-dark">Mis Informes</span>
									</a>
								</li>
								<li class="position-absolute pos-top pos-right d-none d-sm-block text-dark">
									<span class="js-get-date"></span>
								</li>
							</ol>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
			<div class="alert alert-info alert-dismissible fade show p-2 rounded-0 mb-4" role="alert">
				<div class="d-flex align-items-center">
					<div class="alert-icon width-2">
						<span class="icon-stack" style="font-size: 20px;">
							<i class="base-2 icon-stack-3x color-primary-400"></i>
							<i class="base-10 text-white icon-stack-1x"></i>
							<i class="ni md-profile color-primary-800 icon-stack-2x"></i>
						</span>
					</div>
					<div class="flex-1">
						<strong>Acerca De:</strong>
						<span>Modulo para el control de datos de información en la base de datos con múltiples acciones y permisos.</span>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
			<div id="panel-1" class="panel">
				<div class="panel-hdr bg-dark text-white rounded-0">
					<h2 class="text-white">
						<span class="icon-stack fs-xxl mr-2">
							<i class="base base-7 icon-stack-3x opacity-100 color-primary-500"></i>
							<i class="base base-7 icon-stack-2x opacity-100 color-primary-300"></i>
							<i class="<?= $k_mc_ic['lbl_azp_icon_code_t_name']; ?> icon-stack-1x opacity-100 fa-spin"></i>
						</span>
						<span>Mis Informes</span>
					</h2>
					<div class="panel-toolbar">
						<button class="btn btn-panel btn-primary" title="Informacion" data-toggle="modal"
						data-target=".modal-div-info" data-offset="0,10" data-original-title="Informacion"></button>
					</div>
				</div>
				<div class="panel-container show">
					<div class="panel-content p-1">
						<?php $this->insert('backend/design/ds-main/read-field'); ?>
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
								<div class="hide" id="form_ajax_control"></div>
							</div>
							<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 col-xl-10 mb-3">
								<div class="form-group">
									<label class="form-label">
										<span>Filtrar Por: Cedula, Placa O, Tipo Certificado</span>
									</label>
									<div class="input-group input-group-sm input-group-multi-transition">
										<div class="input-group-prepend">
											<button class="btn btn-xs btn-outline-danger" onclick="event_trash_crt();">
												<em class="far fa-trash-alt"></em>
												<span>Limpiar</span>
											</button>
										</div>
										<div class="input-group-prepend">
											<button class="btn btn-xs btn-outline-dark" onclick="event_data_idntf();">
												<em class="far fa-search"></em>
												<span>Buscar</span>
											</button>
										</div>
										<input type="text" name="field_bs_idntf" id="field_bs_idntf" class="form-control border-success" placeholder="Digita la cedula ...">
										<input type="text" name="field_bs_plaqe" id="field_bs_plaqe" class="form-control border-success" placeholder="Digita la placa ...">
										<select name="field_bs_rtype" id="field_bs_rtype" class="custom-select form-control border-success" required="">
											<option value="">Ninguno</option>
											<?php if (false != $df_azp_crt_request_type): ?>
												<?php foreach ($df_azp_crt_request_type as $key): ?>
													<option value="<?= $key[d_azp_crt_request_type_id_azp_crt_request_type]; ?>">
														<?= $key[d_azp_crt_request_type_t_name]; ?>
													</option>
												<?php endforeach; ?>
											<?php else: ?>
												<option value="">No existen resultados</option>
											<?php endif; ?>
										</select>
									</div>
								</div>
							</div>
							<div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2 mb-3">
								<?php if (false != $df_tc_azp_client_image): ?>
									<?php foreach ($df_tc_azp_client_image as $key_img => $value_img): ?>
										<?php $var_document = $value_img[d_azp_fct_client_w_document]; ?>
										<?php $var_route = $value_img[d_azp_fct_client_w_route]; ?>
										<?php $var_folder = $value_img[d_azp_fct_client_w_folder]; ?>
										<?php $var_final = $var_route . $var_folder . $var_document; ?>
										<div class="card border m-auto m-lg-0">
											<img src="<?php echo str_replace('../', '', $var_final); ?>" class="img-preview preview-xs card-img-top">
										</div>
									<?php endforeach; ?>
								<?php endif; ?>
							</div>
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
								<div class="table-responsive">
									<table id="dt_info" cellspacing="0" width="100%" class="text-center table table-bordered table-sm table-hover table-striped w-100 nowrap">
										<thead class="table-success"></thead>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php $this->insert('backend/design/ds-main/file-end'); ?>
	
<script type="text/javascript">
	// Definicion del valor del controlador
	const var_controller = "<?= $df_var_controller; ?>";

	// Ejecutar funcion
	event_data_info();

	function event_data_info() {
		// Column Definitions
		var columnSet = [
			{
				title: "Id",
				id: "lbl_azp_crt_request_data_id_azp_crt_request_data",
				data: "lbl_azp_crt_request_data_id_azp_crt_request_data",
				type: "text",
				className: "text-dark",
				visible: false,
			},
			{
				title: "Cliente",
				id: "lbl_azp_fct_client_t_name",
				data: "lbl_azp_fct_client_t_name",
				type: "text",
				className: "text-dark",
				visible: true,
			},
			{
				title: "Solicitud",
				id: "lbl_azp_crt_request_data_t_request_nro",
				data: "lbl_azp_crt_request_data_t_request_nro",
				type: "text",
				className: "text-dark",
				visible: true,
			},
			{
				title: "Fecha Solicitud",
				id: "lbl_azp_crt_request_data_t_request_date",
				data: "lbl_azp_crt_request_data_t_request_date",
				type: "text",
				className: "text-dark",
				visible: true,
			},
			{
				title: "Registros",
				id: "lbl_azp_crt_request_data_t_count",
				data: "lbl_azp_crt_request_data_t_count",
				type: "text",
				className: "text-dark",
				visible: true,
			},
			{
				title: "Informe",
				id: "lbl_azp_crt_request_data_t_inform_client",
				data: "lbl_azp_crt_request_data_t_inform_client",
				type: "text",
				className: "text-dark",
				visible: true,
			},
		];
		// Inicializar tabla de datos
		var myTable = $('#dt_info').dataTable({
			// Reinicialiar los datos de la tabla
			destroy: true,
			// Estructura de las columnas para el DOOM
			dom: "<'row mb-3'<'col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 d-flex align-items-center'B>>"
				//+ "<'row mb-3'<'col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 d-flex align-items-center justify-content-start'f>"
				//+ "<'col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 d-flex align-items-center justify-content-end'l>>"
				+ "<'row mb-3'<'col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'tr>>"
				+ "<'row mb-3'<'col-xs-12 col-sm-12 col-md-5 col-lg-4 col-xl-4'i><'col-xs-12 col-sm-12 col-md-7 col-lg-8 col-xl-8'p>>",
			// Leer datos de prácticamente cualquier fuente de datos JSON
			ajax: var_controller + "crtbase/",
			// Cargar columnas del encabezado
			columns: columnSet,
			// Opciones para crear, editar, borrar y sincronizar
			altEditor: true,
			// Combinar valores en las demas celdas
			//autoFill: true,
			// Control de funciones Manejo inteligente del ancho de columna
			autoWidth: true,
			// Movilizar columnas en la tabla
			colReorder: true,
			// Creará todos los elementos HTML necesarios por adelantado
			deferRender: true,
			// Fijar columnas en la tabla
			//fixedColumns: true,
			// Fijar columnas en la parte superior de la tabla
			fixedHeader: true,
			// Mostrar entradas de los registros
			info: true,
			// Focalizar una celda de la tabla
			//keys: true,
			// Cambiar numero de registros por pagina
			lengthChange: false,
			// Definir cantidad de registros por paginacion
			lengthMenu: [[10, 20, 30, 40, 50, -1,], [10, 20, 30, 40, 50, 'Todo',],],
			// Ordenar columnas en ascendente o descendente
			order: [[0, 'desc',]],
			// Controlar si las tablas de datos deben usar celda única superior
			orderCellsTop: true,
			// Ordenar segun columna los registros
			ordering: true,
			// Paginar registros limitadamente
			paging: true,
			// Procesando informacion de registros
			processing: true,
			// Control para el tamaño de la tabla de datos
			responsive: true,
			// Agrupar las filas de los registros
			//rowGroup: true,
			// Control de busqueda de registros
			searching: true,
			// Selccionar varias filas de registro
			select: 'single',
			// Procesamiento del lado del servidor
			//serverSide: true,
			// Permite dibujar grandes conjuntos de datos en la pantalla muy rápidamente
			//scroller: true,
			// Control para el desplazamiento medido de arriba abajo
			//scrollCollapse: true,
			// Control para el desplazamiento de derecha a izquiera
			scrollX: true,
			// Control para el desplazamiento medido de arriba abajo
			scrollY: 300,
			// Guardar el estado de una tabla (su posición de paginación, estado de pedido, etc.)
			stateSave: false,
			// Botones que usan clases de bootstrap
			buttons: [
				{
					text: '<i class="far fa-sync"></i> Sincronizar',
					titleAttr: 'Sincronizar',
					name: 'refresh',
					className: 'btn-sm btn-outline-primary',
					attr: {
						'id': 'table_btn_sync',
						'name': 'table_btn_sync',
					},
				},
				{
					text: '<i class="far fa-align-center"></i> Detalle Base',
					titleAttr: 'Detalle Base',
					className: 'btn-sm btn-outline-info',
					attr: {
						'id': 'table_btn_detail',
						'name': 'table_btn_detail',
						'onclick': 'event_detail();',
					},
				},
				{
					text: '<i class="far fa-chart-bar"></i> Informe Cliente',
					titleAttr: 'Informe Cliente',
					className: 'btn-sm btn-outline-success',
					attr: {
						'id': 'table_btn_download',
						'name': 'table_btn_download',
						'onclick': 'event_cl_information();',
					},
				},
				{
					extend: 'copyHtml5',
					text: '<i class="far fa-copy"></i>',
					titleAttr: 'Copiar',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_copy',
						'name': 'table_btn_copy',
					},
				},
				{
					extend: 'pdfHtml5',
					text: '<i class="far fa-file-pdf"></i>',
					titleAttr: 'PDF',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_pdf',
						'name': 'table_btn_pdf',
					},
				},
				{
					extend: 'excelHtml5',
					text: '<i class="far fa-file-excel"></i>',
					titleAttr: 'Excel',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_excel',
						'name': 'table_btn_excel',
					},
				},
				{
					extend: 'csvHtml5',
					text: '<i class="far fa-file-csv"></i>',
					titleAttr: 'CSV',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_csv',
						'name': 'table_btn_csv',
					},
				},
				{
					autoPrint: true,
					extend: 'print',
					text: '<i class="far fa-print"></i>',
					titleAttr: 'Imprimir',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_print',
						'name': 'table_btn_print',
					},
				},
				{
					columns: [1, 2, 3, 4, 5,],
					extend: 'columnToggle',
					text: '<i class="far fa-low-vision"></i>',
					titleAttr: 'Extender',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_column_toggle',
						'name': 'table_btn_column_toggle',
					},
				},
				{
					extend: 'colvisRestore',
					text: '<i class="far fa-low-vision"></i>',
					titleAttr: 'Restaurar',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_colvis_restore',
						'name': 'table_btn_colvis_restore',
					},
				},
				{
					extend: 'colvis',
					text: '<i class="far fa-low-vision"></i>',
					titleAttr: 'Visible',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_colvis_column',
						'name': 'table_btn_colvis_column',
					},
				},
				{
					extend: 'pageLength',
					text: '<i class="far fa-database"></i> Paginacion',
					titleAttr: 'Paginacion',
					className: 'btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_page_length',
						'name': 'table_btn_page_length',
					},
				},
			],
			// Establecer propiedades de inicialización de definición de columna.
			columnDefs: [
				{
					targets: 5,
					render: function(data, type, full, meta) {
						var badge = {
							'Si': {
								'title': 'Si',
								'class': 'badge-success'
							},
							'No': {
								'title': 'No',
								'class': 'badge-danger'
							},
							'null': {
								'title': 'No',
								'class': 'badge-danger'
							},
							'': {
								'title': 'No',
								'class': 'badge-danger'
							},
						};
						if (typeof badge[data] === 'undefined') { return data; }
						return '<span class="badge ' + badge[data].class + ' badge-pill">' + badge[data].title + '</span>';
					},
				},
			],
		});
		// Filtrar valores de los campos
		$('input.column_filter').on(
			'change click keyup', function () {
				event_filter_column(
					$(this).parents('tr').attr('data-column')
				);
			}
		);
		// Asingacion de valores e indices
		for (var i = 0; i <= 6; i++) {
			// Control de validacion existente
			if ($("#filter_col_" + i).length) {
				// Identificar el id del campo
				let input = document.getElementById("col_" + i + "_filter");
				// Asignacion de valor a la propiedad del input
				input.placeholder = columnSet[i]['title'];
				// Asignacion de valor a la propiedad del input
				input.type = columnSet[i]['type'];
			}
		}
		// Asingacion de valores e indices
		for (var i = 7; i <= columnSet.length - 1; i++) {
			// Control de validacion existente
			if ($("#filter_col_" + i).length) {
				let input = document.getElementById("col_" + i + "_filter");
				// Asignacion de valor a la propiedad del input
				input.placeholder = columnSet[i]['title'];
				// Asignacion de valor a la propiedad del input
				input.type = columnSet[i]['type'];
			}
		}
	};

	function event_data_idntf() {
		const ft_idntf = document.getElementById("field_bs_idntf").value;
		const ft_plaqe = document.getElementById("field_bs_plaqe").value;
		const ft_rtype = document.getElementById("field_bs_rtype").value;
		// Column Definitions
		var columnSet = [
			{
				title: "Id",
				id: "lbl_azp_crt_request_data_id_azp_crt_request_data",
				data: "lbl_azp_crt_request_data_id_azp_crt_request_data",
				type: "text",
				className: "text-dark",
				visible: false,
			},
			{
				title: "Cliente",
				id: "lbl_azp_fct_client_t_name",
				data: "lbl_azp_fct_client_t_name",
				type: "text",
				className: "text-dark",
				visible: true,
			},
			{
				title: "Solicitud",
				id: "lbl_azp_crt_request_data_t_request_nro",
				data: "lbl_azp_crt_request_data_t_request_nro",
				type: "text",
				className: "text-dark",
				visible: true,
			},
			{
				title: "Fecha Solicitud",
				id: "lbl_azp_crt_request_data_t_request_date",
				data: "lbl_azp_crt_request_data_t_request_date",
				type: "text",
				className: "text-dark",
				visible: true,
			},
			{
				title: "Registros",
				id: "lbl_azp_crt_request_data_t_count",
				data: "lbl_azp_crt_request_data_t_count",
				type: "text",
				className: "text-dark",
				visible: true,
			},
			{
				title: "Informe",
				id: "lbl_azp_crt_request_data_t_inform_client",
				data: "lbl_azp_crt_request_data_t_inform_client",
				type: "text",
				className: "text-dark",
				visible: true,
			},
		];
		// Inicializar tabla de datos
		var myTable = $('#dt_info').dataTable({
			// Reinicialiar los datos de la tabla
			destroy: true,
			// Estructura de las columnas para el DOOM
			dom: "<'row mb-3'<'col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 d-flex align-items-center'B>>"
				//+ "<'row mb-3'<'col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 d-flex align-items-center justify-content-start'f>"
				//+ "<'col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 d-flex align-items-center justify-content-end'l>>"
				+ "<'row mb-3'<'col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12'tr>>"
				+ "<'row mb-3'<'col-xs-12 col-sm-12 col-md-5 col-lg-4 col-xl-4'i><'col-xs-12 col-sm-12 col-md-7 col-lg-8 col-xl-8'p>>",
			// Leer datos de prácticamente cualquier fuente de datos JSON
			ajax: var_controller + "crtidntf/?field_idntf=" + ft_idntf + '&field_plaqe=' + ft_plaqe + '&field_rtype=' + ft_rtype,
			// Cargar columnas del encabezado
			columns: columnSet,
			// Opciones para crear, editar, borrar y sincronizar
			altEditor: true,
			// Combinar valores en las demas celdas
			//autoFill: true,
			// Control de funciones Manejo inteligente del ancho de columna
			autoWidth: true,
			// Movilizar columnas en la tabla
			colReorder: true,
			// Creará todos los elementos HTML necesarios por adelantado
			deferRender: true,
			// Fijar columnas en la tabla
			//fixedColumns: true,
			// Fijar columnas en la parte superior de la tabla
			fixedHeader: true,
			// Mostrar entradas de los registros
			info: true,
			// Focalizar una celda de la tabla
			//keys: true,
			// Cambiar numero de registros por pagina
			lengthChange: false,
			// Definir cantidad de registros por paginacion
			lengthMenu: [[10, 20, 30, 40, 50, -1,], [10, 20, 30, 40, 50, 'Todo',],],
			// Ordenar columnas en ascendente o descendente
			order: [[0, 'desc',]],
			// Controlar si las tablas de datos deben usar celda única superior
			orderCellsTop: true,
			// Ordenar segun columna los registros
			ordering: true,
			// Paginar registros limitadamente
			paging: true,
			// Procesando informacion de registros
			processing: true,
			// Control para el tamaño de la tabla de datos
			responsive: true,
			// Agrupar las filas de los registros
			//rowGroup: true,
			// Control de busqueda de registros
			searching: true,
			// Selccionar varias filas de registro
			select: 'single',
			// Procesamiento del lado del servidor
			//serverSide: true,
			// Permite dibujar grandes conjuntos de datos en la pantalla muy rápidamente
			//scroller: true,
			// Control para el desplazamiento medido de arriba abajo
			//scrollCollapse: true,
			// Control para el desplazamiento de derecha a izquiera
			scrollX: true,
			// Control para el desplazamiento medido de arriba abajo
			scrollY: 300,
			// Guardar el estado de una tabla (su posición de paginación, estado de pedido, etc.)
			stateSave: false,
			// Botones que usan clases de bootstrap
			buttons: [
				{
					text: '<i class="far fa-sync"></i> Sincronizar',
					titleAttr: 'Sincronizar',
					name: 'refresh',
					className: 'btn-sm btn-outline-primary',
					attr: {
						'id': 'table_btn_sync',
						'name': 'table_btn_sync',
					},
				},
				{
					text: '<i class="far fa-align-center"></i> Detalle Base',
					titleAttr: 'Detalle Base',
					className: 'btn-sm btn-outline-info',
					attr: {
						'id': 'table_btn_detail',
						'name': 'table_btn_detail',
						'onclick': 'event_detail();',
					},
				},
				{
					text: '<i class="far fa-chart-bar"></i> Informe Cliente',
					titleAttr: 'Informe Cliente',
					className: 'btn-sm btn-outline-success',
					attr: {
						'id': 'table_btn_download',
						'name': 'table_btn_download',
						'onclick': 'event_cl_information();',
					},
				},
				{
					extend: 'copyHtml5',
					text: '<i class="far fa-copy"></i>',
					titleAttr: 'Copiar',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_copy',
						'name': 'table_btn_copy',
					},
				},
				{
					extend: 'pdfHtml5',
					text: '<i class="far fa-file-pdf"></i>',
					titleAttr: 'PDF',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_pdf',
						'name': 'table_btn_pdf',
					},
				},
				{
					extend: 'excelHtml5',
					text: '<i class="far fa-file-excel"></i>',
					titleAttr: 'Excel',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_excel',
						'name': 'table_btn_excel',
					},
				},
				{
					extend: 'csvHtml5',
					text: '<i class="far fa-file-csv"></i>',
					titleAttr: 'CSV',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_csv',
						'name': 'table_btn_csv',
					},
				},
				{
					autoPrint: true,
					extend: 'print',
					text: '<i class="far fa-print"></i>',
					titleAttr: 'Imprimir',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_print',
						'name': 'table_btn_print',
					},
				},
				{
					columns: [1, 2, 3, 4, 5,],
					extend: 'columnToggle',
					text: '<i class="far fa-low-vision"></i>',
					titleAttr: 'Extender',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_column_toggle',
						'name': 'table_btn_column_toggle',
					},
				},
				{
					extend: 'colvisRestore',
					text: '<i class="far fa-low-vision"></i>',
					titleAttr: 'Restaurar',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_colvis_restore',
						'name': 'table_btn_colvis_restore',
					},
				},
				{
					extend: 'colvis',
					text: '<i class="far fa-low-vision"></i>',
					titleAttr: 'Visible',
					className: 'd-none btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_colvis_column',
						'name': 'table_btn_colvis_column',
					},
				},
				{
					extend: 'pageLength',
					text: '<i class="far fa-database"></i> Paginacion',
					titleAttr: 'Paginacion',
					className: 'btn-sm btn-outline-dark',
					attr: {
						'id': 'table_btn_page_length',
						'name': 'table_btn_page_length',
					},
				},
			],
			// Establecer propiedades de inicialización de definición de columna.
			columnDefs: [
				{
					targets: 5,
					render: function(data, type, full, meta) {
						var badge = {
							'Si': {
								'title': 'Si',
								'class': 'badge-success'
							},
							'No': {
								'title': 'No',
								'class': 'badge-danger'
							},
							'null': {
								'title': 'No',
								'class': 'badge-danger'
							},
							'': {
								'title': 'No',
								'class': 'badge-danger'
							},
						};
						if (typeof badge[data] === 'undefined') { return data; }
						return '<span class="badge ' + badge[data].class + ' badge-pill">' + badge[data].title + '</span>';
					},
				},
			],
		});
		// Filtrar valores de los campos
		$('input.column_filter').on(
			'change click keyup', function () {
				event_filter_column(
					$(this).parents('tr').attr('data-column')
				);
			}
		);
		// Asingacion de valores e indices
		for (var i = 0; i <= 6; i++) {
			// Control de validacion existente
			if ($("#filter_col_" + i).length) {
				// Identificar el id del campo
				let input = document.getElementById("col_" + i + "_filter");
				// Asignacion de valor a la propiedad del input
				input.placeholder = columnSet[i]['title'];
				// Asignacion de valor a la propiedad del input
				input.type = columnSet[i]['type'];
			}
		}
		// Asingacion de valores e indices
		for (var i = 7; i <= columnSet.length - 1; i++) {
			// Control de validacion existente
			if ($("#filter_col_" + i).length) {
				let input = document.getElementById("col_" + i + "_filter");
				// Asignacion de valor a la propiedad del input
				input.placeholder = columnSet[i]['title'];
				// Asignacion de valor a la propiedad del input
				input.type = columnSet[i]['type'];
			}
		}
		// Recargar la tabla con nueva informacion
		if ($("#dt_info").length) { $('#dt_info').DataTable().ajax.reload(); }
	};

	function event_trash_crt() {
		document.getElementById('field_bs_idntf').value = '';
		document.getElementById('field_bs_plaqe').value = '';
		event_data_info();
	};

	function event_up_base() {
		// Recargar la tabla con nueva informacion
		if ($("#dt_info").length) { $('#dt_info').DataTable().ajax.reload(); }
	};

	function event_detail() {
		// Activar columnas especificadas de la tabla
		var vtable = $('#dt_info').DataTable();
		vtable.column(0).visible(true);
		// Obtener el primer valor seleccionado de la tabla
		var idtbl = $("#dt_info tr.selected td:first").html();
		// Validar si el id es mayor a cero
		if (idtbl > 0) {
			// Activar columnas especificadas de la tabla
			var vtable = $('#dt_info').DataTable();
			vtable.column(0).visible(false);
			window.location.href = 'azpcrtrequestdata/info/' + idtbl + '/';
		} else {
			// Activar columnas especificadas de la tabla
			var vtable = $('#dt_info').DataTable();
			vtable.column(0).visible(false);
			// Mensaje de audio para mostrar en la pagina web
			initApp.playSound('views/templates/smart/dist/media/sound', 'voice_on');
			bootbox.alert({
				size: "small",
				title: "<i class='fal fa-times-circle text-danger mr-2'></i> <span class='text-danger fw-500'>Error!</span>",
				message: "<span><strong>Lo sentimos:</strong> No haz seleccionado ningun registro.</span>",
				centerVertical: true,
				className: "modal-alert",
				closeButton: false,
			});
		}
	};

	function event_cl_information() {
		// Mostrar la columna especificada de la tabla
		var vtable = $('#dt_info').DataTable();
		vtable.column(0).visible(true);
		// Obtener el primer valor seleccionado de la tabla
		//var idtbl = document.getElementById('field_md_id').value;
		var idtbl = $("#dt_info tr.selected td:first").html();
		// Validar si el id es mayor a cero
		if (idtbl > 0) {
			// Definir los iconos para los correspondientes mensajes
			var error_icon = '<span class="far fa-times-circle" aria-hidden="true"></span>' + ' ';
			var success_icon = '<span class="far fa-check-circle" aria-hidden="true"></span>' + ' ';
			var process_icon = '<span class="far fa-spinner fa-spin" aria-hidden="true"></span>' + ' ';
			// Añadir y remover las clases incorporadas de las hojas de estilo
			$('#form_ajax_control').removeClass('alert-danger');
			$('#form_ajax_control').removeClass('alert-success');
			$('#form_ajax_control').removeClass('alert-warning');
			// Añadir y remover las clases incorporadas de las hojas de estilo
			$('#form_ajax_control').addClass('alert-warning');
			$("#form_ajax_control").html(process_icon  + 'Advertencia: Procesando información, por favor espere...');
			$('#form_ajax_control').removeClass('hide');
			$('#form_ajax_control').addClass('alert');
			var request = (window.XMLHttpRequest) ? new XMLHttpRequest() : new ActiveXObject('Microsoft.XMLHTTP');
			var ajaxurl = var_url + "dashboard/cpcrtdetail/" + idtbl + "/";
			request.open("GET", ajaxurl, true);
			request.send();
			//$('#modal-id-detail').modal('show');
			request.onreadystatechange = function(){
				if (request.readyState == 4 && request.status == 200) {
					var objData = JSON.parse(request.responseText);
					if (objData.status) {
						var fdocument = objData.data.lbl_azp_crt_information_w_document;
						if (fdocument == '' || fdocument == 'null') {
							setTimeout(function() {
								$('#form_ajax_control').removeClass('alert');
								$('#form_ajax_control').addClass('hide');
								$('#form_ajax_control').html('');
							}, 0);
							// Mensaje de audio para mostrar en la pagina web
							initApp.playSound('views/templates/smart/dist/media/sound', 'voice_on');
							bootbox.alert({
								size: "small",
								title: "<i class='fal fa-times-circle text-warning mr-2'></i> <span class='text-warning fw-500'>Advertencia!</span>",
								message: "<span><strong>Lo sentimos: El registro no contiene archivo.",
								centerVertical: true,
								className: "modal-alert",
								closeButton: false,
							});
							// Mostrar la columna especificada de la tabla
							var vtable = $('#dt_info').DataTable();
							vtable.column(0).visible(false);
						} else {
							$('#form_ajax_control').removeClass('alert-danger');
							$('#form_ajax_control').removeClass('alert-success');
							$('#form_ajax_control').removeClass('alert-warning');
							$('#form_ajax_control').addClass('alert-success');
							$("#form_ajax_control").html(success_icon  + 'Exito: Archivo encontrado correctamente.');
							$('#form_ajax_control').removeClass('hide');
							setTimeout(function() {
								$('#form_ajax_control').removeClass('alert');
								$('#form_ajax_control').addClass('hide');
								$('#form_ajax_control').html('');
							}, 5000);
							// Mostrar la columna especificada de la tabla
							var vtable = $('#dt_info').DataTable();
							vtable.column(0).visible(false);
							// Definiendo valores de la busqueda de resultados
							var wdocument = objData.data.lbl_azp_crt_information_w_document;
							var wfolder = objData.data.lbl_azp_crt_information_w_folder;
							var wname = objData.data.lbl_azp_crt_information_w_name;
							var wroute = objData.data.lbl_azp_crt_information_w_route;
							console.log(wroute + wfolder + wdocument);
							var a = $("<a>").attr("href", var_url + wroute.replace('../','') + wfolder + wdocument).attr("download", wname).appendTo("body");
							a[0].click();
							a.remove();
						}
					} else {
						setTimeout(function() {
							$('#form_ajax_control').removeClass('alert');
							$('#form_ajax_control').addClass('hide');
							$('#form_ajax_control').html('');
						}, 0);
						// Mostrar la columna especificada de la tabla
						var vtable = $('#dt_info').DataTable();
						vtable.column(0).visible(false);
						// Mensaje de audio para mostrar en la pagina web
						initApp.playSound('views/templates/smart/dist/media/sound', 'voice_on');
						bootbox.alert({
							size: "small",
							title: "<i class='fal fa-times-circle text-danger mr-2'></i> <span class='text-danger fw-500'>Error!</span>",
							message: "<span><strong>Lo sentimos: El registro no contiene archivo.",
							centerVertical: true,
							className: "modal-alert",
							closeButton: false,
						});
					}
				}
			}
		} else {
			// Mostrar la columna especificada de la tabla
			var vtable = $('#dt_info').DataTable();
			vtable.column(0).visible(false);
			// Mensaje de audio para mostrar en la pagina web
			initApp.playSound('views/templates/smart/dist/media/sound', 'voice_on');
			bootbox.alert({
				size: "small",
				title: "<i class='fal fa-times-circle text-danger mr-2'></i> <span class='text-danger fw-500'>Error!</span>",
				message: "<span><strong>Lo sentimos:</strong> No haz seleccionado ningun registro.</span>",
				centerVertical: true,
				className: "modal-alert",
				closeButton: false,
			});
		}
	};
</script>

</body>
</html>