<?php $this->insert('backend/design/ds-main/email-file-start'); ?>
	<div class="row">
		<!--<div class="col-xs-12 col-sm-10 col-md-8 col-lg-8 col-xl-7">-->
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 mb-3">
					<img src="views/backend/images/gsc_ten.png">
					<img src="views/backend/images/outsourcing.png">
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 mb-3">
					<h3 class="text-dark position-absolute pos-bottom pos-right">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								Bogotá, <?= actual_date(); ?>
							</div>
						</div>
					</h3>
				</div>
				<!--<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
					<h2 class="text-dark text-center">
						<div class="m-0 d-flex fw-500">
							<div class="flex-1 text-contrast">
								ASUNTO: Envío Consignación - Solicitud Expedición Certificados de Defunción
							</div>
						</div>
					</h2>
				</div>-->
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								<span>Señores:</span><br />
								<span>ENTIDAD</span><br />
								<span>Atn: Dra. Según aplique</span><br />
							</div>
						</div>
					</p>
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								Ref.: Entrega Documentos originales.
							</div>
						</div>
					</p>
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								Por medio de la presente, nos permitimos adjuntar certificado(s) de Defunción(s) según su solicitud correspondiente.
							</div>
						</div>
					</p>
					<div class="table-responsive">
						<table class="text-center table table-bordered table-sm table-hover table-striped w-100" cellspacing="0" width="100%">
							<thead class="bg-danger text-white">
								<tr>
									<th>CEDULA</th>
									<th>NOMBRE</th>
									<th>SERIAL</th>
									<th>CIUDAD</th>
									<th>SOLICITUD</th>
									<th>FECHA DE DEFUNCION</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1546456</td>
									<td>Prueba Prueba</td>
									<td>X45689</td>
									<td>Bogota</td>
									<td>Segun Aplique</td>
									<td>Fecha de Defuncion</td>
								</tr>
								<tr>
									<td>1546456</td>
									<td>Prueba Prueba</td>
									<td>X45689</td>
									<td>Bogota</td>
									<td>Segun Aplique</td>
									<td>Fecha de Defuncion</td>
								</tr>
								<tr>
									<td>1546456</td>
									<td>Prueba Prueba</td>
									<td>X45689</td>
									<td>Bogota</td>
									<td>Segun Aplique</td>
									<td>Fecha de Defuncion</td>
								</tr>
							</tbody>
						</table>
					</div>
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								<span>Cualquier inquietud con gusto será atendida.</span><br />
								<span>Coordialmente</span><br />
							</div>
						</div>
					</p>
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								<img src="views/backend/images/firma_doctora.png"
								style="display: block; width: 160px; height: 110px; min-width: 0px !important;
								min-height: 0px !important; max-width: none !important; max-height: none !important;
								transform: translateX(-16px) translateY(-16.2807px);">
							</div>
						</div>
					</p>
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								<b>MARGARITA GIRALDO DE SANCHEZ</b><br />
								<b>Directora de procesos</b><br />
								<b>DG</b><br />
							</div>
						</div>
					</p>
					<div class="progress progress-xs">
						<div class="progress-bar bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 mb-3">
					<div class="row text-center">
						<div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2 mb-3">
							<p class="text-dark">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										<i class="far fa-map-marker-alt fa-3x"></i>
									</div>
								</div>
							</p>
						</div>
						<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 col-xl-10 mb-3">
							<p class="text-dark">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										Carrera 16A No. 78-11 Oficina. 302
									</div>
								</div>
							</p>
							<p class="text-dark">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										Bogotá - Colombia
									</div>
								</div>
							</p>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 mb-3">
					<div class="row text-center">
						<div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2 mb-3">
							<p class="text-dark">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										<i class="far fa-phone-alt fa-3x"></i>
									</div>
								</div>
							</p>
						</div>
						<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 col-xl-10 mb-3">
							<p class="">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										<span>PBX.: (571) 747 5050</span>
										<span class="text-info"><ins> gerencia@gsco.com.co </ins></span>
									</div>
								</div>
							</p>
							<p class="">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										<span>Cel.: 317 796 1603</span>
										<span class="text-info"><ins> www.gsco.com.co </ins></span>
									</div>
								</div>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php $this->insert('backend/design/ds-main/email-file-end'); ?>