<?php $this->insert('backend/design/ds-main/email-file-start'); ?>
	<div class="row">
		<!--<div class="col-xs-12 col-sm-10 col-md-8 col-lg-8 col-xl-7">-->
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 mb-3">
					<img src="views/backend/images/gsc_ten.png">
					<img src="views/backend/images/outsourcing.png">
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 mb-3">
					<h3 class="text-dark position-absolute pos-bottom pos-right">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								Bogotá, <?= actual_date(); ?>
							</div>
						</div>
					</h3>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
					<h2 class="text-dark text-center">
						<div class="m-0 d-flex fw-500">
							<div class="flex-1 text-contrast">
								ASUNTO: ENVÍO CONSIGNACIÓN - SOLICITUD EXPEDICIÓN CERTIFICADOS DE DEFUNCIÓN
							</div>
						</div>
					</h2>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								Señores:
							</div>
						</div>
					</p>
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								NOTARIA xxxx
							</div>
						</div>
					</p>
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								De acuerdo con confirmación de la existencia de (los) siguiente(s) certificado(s) en referencia en esa notaria, adjuntamos consignación por $xxxxxx, solictando lea expedición y envío de los mismo.
							</div>
						</div>
					</p>
					<div class="table-responsive">
						<table class="text-center table table-bordered table-sm table-hover table-striped w-100" cellspacing="0" width="100%">
							<thead class="bg-danger text-white">
								<tr>
									<th>CEDULA</th>
									<th>NOMBRE</th>
									<th>SERIAL</th>
									<th>NOTARIA</th>
									<th>CIUDAD</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1546456</td>
									<td>Prueba Prueba</td>
									<td>X45689</td>
									<td>Nro 1</td>
									<td>Bogota</td>
								</tr>
								<tr>
									<td>1546456</td>
									<td>Prueba Prueba</td>
									<td>X45689</td>
									<td>Nro 1</td>
									<td>Bogota</td>
								</tr>
								<tr>
									<td>1546456</td>
									<td>Prueba Prueba</td>
									<td>X45689</td>
									<td>Nro 1</td>
									<td>Bogota</td>
								</tr>
							</tbody>
						</table>
					</div>
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								<b>Carrera 16 A # 78-11 Ofi. 302</b><br />
								<b>MARGARITA GIRALDO</b><br />
								<b>TELEFONO 7475050 Ext 1587</b><br />
								<b>BOGOTÁ</b>
							</div>
						</div>
					</p>
					<p class="text-dark">
						<div class="m-0 d-flex">
							<div class="flex-1 text-contrast">
								Cordial saludo
							</div>
						</div>
					</p>
					<div class="progress progress-xs">
						<div class="progress-bar bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 mb-3">
					<div class="row text-center">
						<div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2 mb-3">
							<p class="text-dark">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										<i class="far fa-map-marker-alt fa-3x"></i>
									</div>
								</div>
							</p>
						</div>
						<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 col-xl-10 mb-3">
							<p class="text-dark">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										Carrera 16A No. 78-11 Oficina. 302
									</div>
								</div>
							</p>
							<p class="text-dark">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										Bogotá - Colombia
									</div>
								</div>
							</p>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 mb-3">
					<div class="row text-center">
						<div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2 mb-3">
							<p class="text-dark">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										<i class="far fa-phone-alt fa-3x"></i>
									</div>
								</div>
							</p>
						</div>
						<div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 col-xl-10 mb-3">
							<p class="">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										<span>PBX.: (571) 747 5050</span>
										<span class="text-info"><ins> gerencia@gsco.com.co </ins></span>
									</div>
								</div>
							</p>
							<p class="">
								<div class="m-0 d-flex">
									<div class="flex-1 text-contrast">
										<span>Cel.: 317 796 1603</span>
										<span class="text-info"><ins> www.gsco.com.co </ins></span>
									</div>
								</div>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php $this->insert('backend/design/ds-main/email-file-end'); ?>