<!DOCTYPE html>
<html lang="es">
<head>
	<base href="<?= URL; ?>" />
	<title><?= APP; ?></title>
	<meta charset="utf-8">

	<link rel="apple-touch-icon" sizes="180x180" href="views/templates/smart/dist/img/favicon/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="views/templates/smart/dist/img/favicon/favicon-32x32.png">
	<link rel="mask-icon" href="views/templates/smart/dist/img/favicon/safari-pinned-tab.svg" color="#5bbad5">

	<link href="views/templates/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<link href="views/frontend/css/product.css" rel="stylesheet">
</head>
<body>