<?php $this->insert('backend/design/ds-main/file-start'); ?>
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
			<div class="h-alt-hf d-flex flex-column align-items-center justify-content-center text-center">
				<h1 class="page-error color-fusion-500">
					Error De <span class="text-gradient">Archivo</span>
				</h1>
				<div class="alert alert-warning pt-4 pr-5 pb-3 pl-5" id="demo-alert">
					<h1 class="fs-xxl fw-700 color-fusion-500 d-flex align-items-center justify-content-center m-0">
						<span class="color-danger-700">Oops! Archivo No Encontrado</span>
					</h1>
					<h3 class="fw-500 mb-0 mt-3">
						Ha experimentado un error técnico.
					</h3>
					<p class="container container-sm mb-0 mt-1">
						No te preocupes si has ingresado a una archivo inexistente.
					</p>
					<p class="container container-sm mb-0 mt-1">
						Puedes continuar navegando en los diferentes modulos de la plataforma web.
					</p>
					<div class="mt-4">
						<a href="dashboard/" class="btn btn-sm btn-outline-primary waves-effect waves-light">
							<span class="fw-700">Voler al Panel de Control</span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php $this->insert('backend/design/ds-main/file-end'); ?>