<?= $this->insert('frontend/design/file-start'); ?>
	<main id="main">
		<section id="breadcrumbs" class="breadcrumbs">
			<div class="container">
				<ol>
					<li>
						<a href="home/">
							<span>Inicio</span>
						</a>
					</li>
					<li>
						<a href="contact/">
							<span>Contacto</span>
						</a>
					</li>
				</ol>
				<h4>
					Contactanos en <?= APP; ?>
				</h4>
			</div>
		</section>
		<section id="contact" class="contact">
			<div class="container">
				<div class="section-title">
					<h3><span>¿Que Esperas?</span></h3>
					<p><?= APP; ?> te conecta mejor con nosotros</p>
					<p><?= APP; ?> te muestra los mejores productos</p>
				</div>
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
								<div class="info">
									<div class="email">
										<i class="icofont-google-map"></i>
										<h4>Localizacion:</h4>
										<p>Mi Direccion</p>
									</div>
								</div>
							</div>
							<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
								<div class="info">
									<div class="email">
										<i class="icofont-envelope"></i>
										<h4>Contacto:</h4>
										<p>email@gmail.com</p>
									</div>
								</div>
							</div>
							<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
								<div class="info">
									<div class="email">
										<i class="icofont-phone"></i>
										<h4>Llamame:</h4>
										<p>+57 300 000 00 00</p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<form class="form-horizontal" role="form" enctype="application/x-www-form-urlencoded" id="form_zz_contact">
							<div class="row mt-4">
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<div class="alert hide" id="ajax_zz_contact"></div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
									<div class="form-group">
										<label for="field_names">
											<span>Nombres:</span>
										</label>
										<input type="text" name="field_names" id="field_names" class="form-control" placeholder="Digita el texto ..." required="">
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
									<div class="form-group">
										<label for="field_surnames">
											<span>Apellidos:</span>
										</label>
										<input type="text" name="field_surnames" id="field_surnames" class="form-control" placeholder="Digita el texto ..." required="">
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
									<div class="form-group">
										<label for="field_phone_fixed">
											<span>Telefono Fijo:</span>
										</label>
										<input type="number" name="field_phone_fixed" id="field_phone_fixed" class="form-control" placeholder="Digita el texto ..." required="">
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
									<div class="form-group">
										<label for="field_phone_movil">
											<span>Telefono Movil:</span>
										</label>
										<input type="number" name="field_phone_movil" id="field_phone_movil" class="form-control" placeholder="Digita el texto ..." required="">
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
									<div class="form-group">
										<label for="field_email">
											<span>Correo Electronico:</span>
										</label>
										<input type="text" name="field_email" id="field_email" class="form-control" placeholder="Digita el texto ..." required="">
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
									<div class="form-group">
										<label for="field_country">
											<span>Pais:</span>
										</label>
										<select name="field_country" id="field_country" class="form-control" required="">
											<option value="0">Seleccionar</option>
											<?php if (false != $df_sql_select_tc_azp_country): ?>
												<?php foreach ($df_sql_select_tc_azp_country as $key): ?>
													<option value="<?= $key[d_azp_country_id_azp_country]; ?>">
														<?= $key[d_azp_country_t_name]; ?>
													</option>
												<?php endforeach; ?>
											<?php else: ?>
												<option value="0">No existen resultados</option>
											<?php endif; ?>
										</select>
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
									<div class="form-group">
										<label for="field_affair">
											<span>Asunto:</span>
										</label>
										<input type="text" name="field_affair" id="field_affair" class="form-control" placeholder="Digita el texto ..." required="">
									</div>
								</div>
								<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
									<div class="form-group">
										<label for="field_transact">
											<span>Tramite:</span>
										</label>
										<select name="field_transact" id="field_transact" class="form-control" required="">
											<option value="0">Seleccionar</option>
											<?php if (false != $df_sql_select_tc_azp_transact): ?>
												<?php foreach ($df_sql_select_tc_azp_transact as $key): ?>
													<option value="<?= $key[d_azp_transact_id_azp_transact]; ?>">
														<?= $key[d_azp_transact_t_name]; ?>
													</option>
												<?php endforeach; ?>
											<?php else: ?>
												<option value="0">No existen resultados</option>
											<?php endif; ?>
										</select>
									</div>
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
									<div class="form-group">
										<label for="field_message">
											<span>Mensaje:</span>
										</label>
										<textarea name="field_message" id="field_message" class="form-control form-control-sm" placeholder="Digita el texto ..." required="" rows="5"></textarea>
									</div>
								</div>
								<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center mt-3">
									<div class="form-group">
										<button type="button" id="btn_zz_contact" class="btn btn-md btn-primary btn-custom w-md waves-effect waves-light">
											<span>Enviar</span>
										</button>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</section>
	</main>
<?= $this->insert('frontend/design/file-end'); ?>