<?= $this->insert('frontend/design/file-start'); ?>
	<div class="page-banner no-subtitle">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<h2>Iniciar Sesion</h2>
				</div>
				<div class="col-md-6">
					<ul class="breadcrumbs">
						<li>
							<a href="home/">
								<span>Inicio</span>
							</a>
						</li>
						<li>
							<a href="login/">
								<span>Ingresar</span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div id="content">
		<div class="container">
			<div class="row">
				
			</div>
		</div>
	</div>
	<section class="py-3 bg-light">
		<div class="container">
			<div class="row text-center">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<div class="row">
						<?php if (false != $df_sql_controller_read): ?>
							<?php foreach ($df_sql_controller_read as $key): ?>
								<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
									<div class="card">
										<div class="card-body p-4">
											<h4 class="header-title zoomIn animated wow" data-wow-delay=".1s">
												<?= $key['lbl_azp_frequent_questions_t_question']; ?>
											</h4>
											<p class="text-custom zoomIn animated wow" data-wow-delay=".2s">
												<?= $key['lbl_azp_frequent_questions_t_answer']; ?>
											</p>
										</div>
									</div>
								</div>
							<?php endforeach; ?>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	</section>
<?= $this->insert('frontend/design/file-end'); ?>