<h4 class="classic-title text-center">
	<span>Informacion</span>
</h4>
<div class="service-box service-icon-left-more">
	<div class="service-icon">
		<i class="fa fa-users icon-medium"></i>
	</div>
	<div class="service-content">
		<h4>
			<span><?= APP; ?> te conecta mejor con nosotros.</span>
		</h4>
	</div>
</div>
<div class="service-box service-icon-left-more">
	<div class="service-icon">
		<i class="fa fa-users icon-medium"></i>
	</div>
	<div class="service-content">
		<h4>
			<span><?= APP; ?> te muestra los mejores productos.</span>
		</h4>
	</div>
</div>
<div class="service-box service-icon-left-more">
	<div class="service-icon">
		<i class="fa fa-users icon-medium"></i>
	</div>
	<div class="service-content">
		<h4>
			<span><?= APP; ?> te administra mas facil tus compras.</span>
		</h4>
	</div>
</div>