<?= $this->insert('frontend/design/file-start'); ?>
	<main>
		<div class="album py-5 bg-light">
			<div class="container-fluid">
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
								<img src="views/frontend/images/fondo.png" class="img-fluid">
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
						<div class="col">
							<div class="card shadow-sm">
								<div class="card-body">
									<form class="form-horizontal" role="form" enctype="application/x-www-form-urlencoded" id="form_zz_login">
										<div class="row">
											<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
												<div class="form-group">
													<div class="alert hide" id="ajax_zz_login"></div>
													<?php if (isset($_GET['field_id'])): ?>
														<?php if ($_GET['field_id'] == 'error'): ?>
															<div class="alert alert-danger alert-dismissable">
																<b>Error:</b>
																<span>Haz ingresado incorrectamente al enlace proporcionado.</span>
															</div>
														<?php endif; ?>
														<?php if ($_GET['field_id'] == 'password'): ?>
															<div class="alert alert-success alert-dismissable">
																<b>Exito:</b>
																<span>Tu contraseña fue restaurada correctamente.</span>
															</div>
														<?php endif; ?>
														<?php if ($_GET['field_id'] == 'session'): ?>
															<div class="alert alert-danger alert-dismissable">
																<b>Error:</b>
																<span>No se puedo realizar la accion del registro, vuleve a iniciar sesión nuevamente.</span>
															</div>
														<?php endif; ?>
														<?php if ($_GET['field_id'] == 'url'): ?>
															<div class="alert alert-danger alert-dismissable">
																<b>Error:</b>
																<span>El enlace cargado no es el correcto, corrobora el enlace.</span>
															</div>
														<?php endif; ?>
													<?php endif; ?>
												</div>
											</div>
											<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
												<div class="form-group">
													<label for="field_login" class="form-label">
														<span>Usuario</span>
													</label>
													<div class="input-group input-group-sm">
														<input type="text" name="field_login" id="field_login" class="form-control" placeholder="Digita el texto ..." required="" />
													</div>
												</div>
											</div>
											<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
												<div class="form-group">
													<label for="field_password" class="form-label">
														<span>Contraseña</span>
													</label>
													<div class="input-group input-group-sm">
														<input type="password" name="field_password" id="field_password" class="form-control" placeholder="Digita el texto ..." required="" />
													</div>
												</div>
											</div>
											<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
												<div class="form-group">
													<button type="button" id="btn_zz_login" class="btn btn-sm btn-primary w-100">
														<span>Loguearme</span>
													</button>
												</div>
											</div>
											<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3">
												<div class="text-center">
													<a href="recover/">
														<span>Has olvidado tu contraseña?</span>
													</a>
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</main>
<?= $this->insert('frontend/design/file-end'); ?>